GLVis: aux_vis.cpp File Reference
aux_vis.cpp File Reference
#include <iostream>
#include <sstream>
#include <math.h>
#include <time.h>
#include <X11/keysym.h>
#include "mfem.hpp"
#include "palettes.hpp"
#include "gl2ps.h"
#include "visual.hpp"
Functions
void MyExpose (GLsizei w, GLsizei h)
int InitVisualization (const char name[], int x, int y, int w, int h)
Initializes the visualization and some keys.
void SendKeyEvent (KeySym keysym, int Shift=0)
void SendKeySequence (char *seq)
Send a sequence of keystrokes to the visualization window.
void InitIdleFuncs ()
void SetVisualizationScene (VisualizationScene *scene, int view, char *keys)
Start the infinite visualization loop.
void KillVisualization ()
void SendExposeEvent ()
Send expose event. In our case MyReshape is executed and Draw after it.
void MyReshape (GLsizei w, GLsizei h)
void MyExpose ()
void MainIdleFunc ()
void AddIdleFunc (void(*Func)(void))
void RemoveIdleFunc (void(*Func)(void))
void MainLoop ()
double sqr (double t)
void ComputeSphereAngles (int &newx, int &newy, double &new_sph_u, double &new_sph_t)
void LeftButtonDown (AUX_EVENTREC *event)
void LeftButtonLoc (AUX_EVENTREC *event)
void LeftButtonUp (AUX_EVENTREC *event)
void MiddleButtonDown (AUX_EVENTREC *event)
void MiddleButtonLoc (AUX_EVENTREC *event)
void MiddleButtonUp (AUX_EVENTREC *event)
void RightButtonDown (AUX_EVENTREC *event)
void RightButtonLoc (AUX_EVENTREC *event)
void RightButtonUp (AUX_EVENTREC *event)
int Screenshot (const char *fname)
Take a screenshot using libtiff or xwd.
void KeyS ()
void KeyP ()
void KeyQPressed ()
void ToggleThreads ()
void CheckSpin ()
void Key0Pressed ()
void KeyDeletePressed ()
void KeyEnterPressed ()
void Key7Pressed ()
void Key8Pressed ()
void Key9Pressed ()
void Key4Pressed ()
void Key5Pressed ()
void Key6Pressed ()
void Key1Pressed ()
void Key2Pressed ()
void Key3Pressed ()
void ShiftView (double dx, double dy)
void KeyLeftPressed (GLenum state)
void KeyRightPressed (GLenum state)
void KeyUpPressed (GLenum state)
void KeyDownPressed (GLenum state)
void KeyJPressed ()
void KeyMinusPressed ()
void KeyPlusPressed ()
void ZoomIn ()
void ZoomOut ()
void ScaleUp ()
void ScaleDown ()
void LookAt ()
void ShrinkWindow ()
void EnlargeWindow ()
void MoveResizeWindow (int x, int y, int w, int h)
void Cone ()
void MySetColor (double val, double min, double max)
void MySetColor (double val)
void Make_Texture_From_Palette ()
void Make_Texture_From_Palette_2 ()
void Set_Texture_Image ()
int GetUseTexture ()
void SetUseTexture (int ut)
Variables
int fontbase
int visualize = 0
VisualizationScene * locscene
float MatAlpha = 1.0
float MatAlphaCenter = 0.5
Array< void(*)()> IdleFuncs
int LastIdleFunc
double xang = 0.
double yang = 0.
double srot [16]
double sph_t
double sph_u
int constrained_spinning = 0
const double window_scale_factor = 1.1
int MySetColorLogscale = 0
int RepeatPaletteTimes = 1
int UseTexture = 0
const int Max_Texture_Size = 512
int Texture_Size
GLfloat Texture_Image [3 *Max_Texture_Size]
Function Documentation
void AddIdleFunc (void(*)(void) Func)
Definition at line 399 of file aux_vis.cpp.
References IdleFuncs, and MainIdleFunc().
Referenced by CheckSpin(), KeyDeletePressed(), LeftButtonUp(), ScriptControl(), and SetVisualizationScene().
void CheckSpin ()
Definition at line 847 of file aux_vis.cpp.
References AddIdleFunc(), MainLoop(), RemoveIdleFunc(), VisualizationScene::spinning, and yang.
Referenced by Key0Pressed(), and KeyEnterPressed().
void ComputeSphereAngles (int & newx, int & newy, double & new_sph_u, double & new_sph_t) [inline]
Definition at line 463 of file aux_vis.cpp.
References sqr().
Referenced by LeftButtonDown(), and LeftButtonLoc().
void Cone ()
Definition at line 1124 of file aux_vis.cpp.
Referenced by VisualizationSceneScalarData::Arrow2(), and VisualizationSceneScalarData::Arrow3().
void EnlargeWindow ()
Definition at line 1103 of file aux_vis.cpp.
Referenced by InitVisualization().
int GetUseTexture ()
Definition at line 1302 of file aux_vis.cpp.
References UseTexture.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), VisualizationSceneSolution::Draw(), VisualizationSceneScalarData::DrawColorBar(), KeyF6Pressed(), KeyPPressed(), and VisualizationSceneScalarData::ToggleTexture().
void InitIdleFuncs ()
Definition at line 385 of file aux_vis.cpp.
References IdleFuncs, and LastIdleFunc.
Referenced by SetVisualizationScene().
int InitVisualization (const char name[], int x, int y, int w, int h)
Initializes the visualization and some keys.
Definition at line 37 of file aux_vis.cpp.
References EnlargeWindow(), fontbase, Init_Palettes(), Key0Pressed(), Key1Pressed(), Key2Pressed(), Key3Pressed(), Key4Pressed(), Key5Pressed(), Key6Pressed(), Key7Pressed(), Key8Pressed(), Key9Pressed(), KeyDeletePressed(), KeyDownPressed(), KeyEnterPressed(), KeyJPressed(), KeyLeftPressed(), KeyMinusPressed(), KeyP(), KeyPlusPressed(), KeyQPressed(), KeyRightPressed(), KeyS(), KeyUpPressed(), LeftButtonDown(), LeftButtonLoc(), LeftButtonUp(), LookAt(), MiddleButtonDown(), MiddleButtonLoc(), MiddleButtonUp(), MyExpose(), RightButtonDown(), RightButtonLoc(), RightButtonUp(), ScaleDown(), ScaleUp(), Set_Texture_Image(), SetUseTexture(), ShrinkWindow(), ZoomIn(), and ZoomOut().
Referenced by InitVis().
void Key0Pressed ()
Definition at line 863 of file aux_vis.cpp.
References CheckSpin().
Referenced by InitVisualization().
void Key1Pressed ()
Definition at line 948 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key2Pressed ()
Definition at line 957 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key3Pressed ()
Definition at line 963 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key4Pressed ()
Definition at line 921 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key5Pressed ()
Definition at line 930 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key6Pressed ()
Definition at line 939 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key7Pressed ()
Definition at line 897 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key8Pressed ()
Definition at line 906 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key9Pressed ()
Definition at line 912 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyDeletePressed ()
Definition at line 871 of file aux_vis.cpp.
References AddIdleFunc(), MainLoop(), RemoveIdleFunc(), and yang.
Referenced by InitVisualization().
void KeyDownPressed (GLenum state)
Definition at line 1022 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KeyEnterPressed ()
Definition at line 889 of file aux_vis.cpp.
References CheckSpin().
Referenced by InitVisualization().
void KeyJPressed ()
Definition at line 1035 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyLeftPressed (GLenum state)
Definition at line 983 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KeyMinusPressed ()
Definition at line 1041 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyP ()
Definition at line 789 of file aux_vis.cpp.
Referenced by InitVisualization().
void KeyPlusPressed ()
Definition at line 1047 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyQPressed ()
Definition at line 832 of file aux_vis.cpp.
References visualize.
Referenced by InitVisualization().
void KeyRightPressed (GLenum state)
Definition at line 996 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KeyS ()
Definition at line 766 of file aux_vis.cpp.
References Screenshot().
Referenced by InitVisualization().
void KeyUpPressed (GLenum state)
Definition at line 1009 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KillVisualization ()
Definition at line 310 of file aux_vis.cpp.
References fontbase, and locscene.
Referenced by main(), and StartVisualization().
void LeftButtonDown (AUX_EVENTREC * event)
Definition at line 484 of file aux_vis.cpp.
References ComputeSphereAngles(), MainLoop(), RemoveIdleFunc(), and VisualizationScene::rotmat.
Referenced by InitVisualization().
void LeftButtonLoc (AUX_EVENTREC * event)
Definition at line 501 of file aux_vis.cpp.
References ComputeSphereAngles(), VisualizationScene::rotmat, and SendExposeEvent().
Referenced by InitVisualization().
void LeftButtonUp (AUX_EVENTREC * event)
Definition at line 572 of file aux_vis.cpp.
References AddIdleFunc(), MainLoop(), and yang.
Referenced by InitVisualization().
void LookAt ()
Definition at line 1077 of file aux_vis.cpp.
References SendExposeEvent(), VisualizationScene::ViewCenterX, and VisualizationScene::ViewCenterY.
Referenced by InitVisualization().
void MainIdleFunc ()
Definition at line 392 of file aux_vis.cpp.
References IdleFuncs, and LastIdleFunc.
Referenced by AddIdleFunc().
void MainLoop ()
Definition at line 420 of file aux_vis.cpp.
References Screenshot(), and yang.
Referenced by CheckSpin(), KeyDeletePressed(), KeyrPressed(), KeyRPressed(), LeftButtonDown(), LeftButtonUp(), and SetVisualizationScene().
void Make_Texture_From_Palette ()
Definition at line 1219 of file aux_vis.cpp.
References Max_Texture_Size, RGB_Palette, RGB_Palette_Size, and Texture_Size.
Referenced by Set_Texture_Image().
void Make_Texture_From_Palette_2 ()
Definition at line 1249 of file aux_vis.cpp.
References Max_Texture_Size, RGB_Palette, RGB_Palette_Size, and Texture_Size.
Referenced by Set_Texture_Image().
void MiddleButtonDown (AUX_EVENTREC * event)
Definition at line 594 of file aux_vis.cpp.
Referenced by InitVisualization().
void MiddleButtonLoc (AUX_EVENTREC * event)
Definition at line 600 of file aux_vis.cpp.
References VisualizationScene::OrthogonalProjection, SendExposeEvent(), VisualizationScene::ViewAngle, VisualizationScene::ViewCenterX, VisualizationScene::ViewCenterY, and VisualizationScene::ViewScale.
Referenced by InitVisualization().
void MiddleButtonUp (AUX_EVENTREC * event)
Definition at line 633 of file aux_vis.cpp.
Referenced by InitVisualization().
void MoveResizeWindow (int x, int y, int w, int h)
Definition at line 1117 of file aux_vis.cpp.
Referenced by ExecuteScriptCommand().
void MyExpose (GLsizei w, GLsizei h)
Definition at line 367 of file aux_vis.cpp.
References MyReshape().
Referenced by ExecuteScriptCommand(), InitVisualization(), and MyExpose().
void MyExpose ()
Definition at line 373 of file aux_vis.cpp.
References MyExpose().
void MyReshape (GLsizei w, GLsizei h)
Definition at line 333 of file aux_vis.cpp.
References VisualizationScene::OrthogonalProjection, VisualizationScene::ViewAngle, VisualizationScene::ViewCenterX, VisualizationScene::ViewCenterY, and VisualizationScene::ViewScale.
Referenced by MyExpose().
void MySetColor (double val, double min, double max)
Definition at line 1154 of file aux_vis.cpp.
References MySetColor().
Referenced by VisualizationSceneSolution3d::CuttingPlaneFunc(), VisualizationSceneScalarData::DrawColorBar(), DrawPatch(), DrawQuad(), VisualizationSceneSolution3d::DrawRefinedSurf(), DrawTriangle(), VisualizationSceneVector::DrawVector(), VisualizationSceneVector3d::DrawVector(), MySetColor(), VisualizationSceneVector3d::Prepare(), VisualizationSceneSolution3d::Prepare(), VisualizationSceneSolution::Prepare(), VisualizationSceneVector3d::PrepareCuttingPlane(), and VisualizationSceneSolution3d::PrepareLevelSurf().
void MySetColor (double val)
Definition at line 1169 of file aux_vis.cpp.
References MatAlpha, MatAlphaCenter, RGB_Palette, and RGB_Palette_Size.
void RemoveIdleFunc (void(*)(void) Func)
Definition at line 405 of file aux_vis.cpp.
References IdleFuncs.
Referenced by CheckSpin(), KeyDeletePressed(), KeyrPressed(), KeyRPressed(), LeftButtonDown(), and ScriptControl().
void RightButtonDown (AUX_EVENTREC * event)
Definition at line 636 of file aux_vis.cpp.
Referenced by InitVisualization().
void RightButtonLoc (AUX_EVENTREC * event)
Definition at line 642 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void RightButtonUp (AUX_EVENTREC * event)
Definition at line 685 of file aux_vis.cpp.
Referenced by InitVisualization().
void ScaleDown ()
Definition at line 1071 of file aux_vis.cpp.
References VisualizationScene::Scale(), and SendExposeEvent().
Referenced by InitVisualization().
void ScaleUp ()
Definition at line 1065 of file aux_vis.cpp.
References VisualizationScene::Scale(), and SendExposeEvent().
Referenced by InitVisualization().
int Screenshot (const char * fname)
Take a screenshot using libtiff or xwd.
Definition at line 688 of file aux_vis.cpp.
Referenced by ExecuteScriptCommand(), KeyS(), and MainLoop().
void SendExposeEvent ()
Send expose event. In our case MyReshape is executed and Draw after it.
Definition at line 321 of file aux_vis.cpp.
Referenced by Key1Pressed(), Key2Pressed(), Key3Pressed(), Key4Pressed(), Key5Pressed(), Key6Pressed(), Key7Pressed(), Key8Pressed(), Key9Pressed(), KeyaPressed(), KeyAPressed(), KeyBackslashPressed(), KeyCommaPressed(), KeyCPressed(), KeyDownPressed(), KeyDPressed(), KeyF2Pressed(), KeyF6Pressed(), KeyF7Pressed(), KeyGPressed(), KeyGravePressed(), KeyiPressed(), KeyJPressed(), KeykPressed(), KeyKPressed(), KeyLeftPressed(), KeyLessPressed(), KeylPressed(), KeyLPressed(), KeyMinusPressed(), KeyPlusPressed(), KeyPPressed(), KeyRightPressed(), KeyrPressed(), KeyRPressed(), KeySPressed(), KeyTildePressed(), KeyToggleTexture(), KeyTPressed(), KeyUpPressed(), KeyuPressed(), KeyvPressed(), KeyVPressed(), LeftButtonLoc(), LookAt(), MiddleButtonLoc(), VisualizationSceneVector3d::NPressed(), VisualizationSceneVector::NPressed(), RightButtonLoc(), ScaleDown(), ScaleUp(), SendKeySequence(), ZoomIn(), and ZoomOut().
void SendKeyEvent (KeySym keysym, int Shift = 0)
Definition at line 156 of file aux_vis.cpp.
Referenced by SendKeySequence().
void SendKeySequence (char * seq)
Send a sequence of keystrokes to the visualization window.
Definition at line 187 of file aux_vis.cpp.
References SendExposeEvent(), and SendKeyEvent().
Referenced by ExecuteScriptCommand(), and SetVisualizationScene().
void Set_Texture_Image ()
Definition at line 1272 of file aux_vis.cpp.
References Make_Texture_From_Palette(), and Make_Texture_From_Palette_2().
Referenced by InitVisualization(), Set_Palette(), and SetUseTexture().
void SetUseTexture (int ut)
Definition at line 1307 of file aux_vis.cpp.
References Set_Texture_Image().
Referenced by VisualizationSceneSolution::Init(), VisualizationSceneSolution3d::Init(), InitVisualization(), and VisualizationSceneScalarData::ToggleTexture().
void SetVisualizationScene (VisualizationScene * scene, int view, char * keys)
Start the infinite visualization loop.
Definition at line 288 of file aux_vis.cpp.
References AddIdleFunc(), InitIdleFuncs(), MainLoop(), and SendKeySequence().
Referenced by main(), and StartVisualization().
void ShiftView (double dx, double dy)
Definition at line 972 of file aux_vis.cpp.
References VisualizationScene::OrthogonalProjection, VisualizationScene::ViewAngle, VisualizationScene::ViewCenterX, VisualizationScene::ViewCenterY, and VisualizationScene::ViewScale.
Referenced by KeyDownPressed(), KeyLeftPressed(), KeyRightPressed(), and KeyUpPressed().
void ShrinkWindow ()
Definition at line 1089 of file aux_vis.cpp.
Referenced by InitVisualization().
double sqr (double t) [inline]
Definition at line 458 of file aux_vis.cpp.
Referenced by ComputeSphereAngles().
void ToggleThreads ()
Definition at line 837 of file aux_vis.cpp.
References visualize.
Referenced by StartVisualization().
void ZoomIn ()
Definition at line 1053 of file aux_vis.cpp.
References SendExposeEvent(), and VisualizationScene::Zoom().
Referenced by InitVisualization().
void ZoomOut ()
Definition at line 1059 of file aux_vis.cpp.
References SendExposeEvent(), and VisualizationScene::Zoom().
Referenced by InitVisualization().
Variable Documentation
int constrained_spinning = 0
Definition at line 417 of file aux_vis.cpp.
int fontbase
Definition at line 28 of file aux_vis.cpp.
Referenced by VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawCoordinateCross(), InitVisualization(), KillVisualization(), and VisualizationSceneScalarData::PrepareAxes().
Array<void (*)()> IdleFuncs
Definition at line 382 of file aux_vis.cpp.
Referenced by AddIdleFunc(), InitIdleFuncs(), MainIdleFunc(), and RemoveIdleFunc().
int LastIdleFunc
Definition at line 383 of file aux_vis.cpp.
Referenced by InitIdleFuncs(), and MainIdleFunc().
VisualizationScene* locscene
Definition at line 30 of file aux_vis.cpp.
Referenced by KeyrPressed(), KeyRPressed(), and KillVisualization().
float MatAlpha = 1.0
Definition at line 32 of file aux_vis.cpp.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), VisualizationSceneSolution::Draw(), KeykPressed(), KeyKPressed(), and MySetColor().
float MatAlphaCenter = 0.5
Definition at line 33 of file aux_vis.cpp.
Referenced by KeyCommaPressed(), KeyLessPressed(), and MySetColor().
const int Max_Texture_Size = 512
Definition at line 1215 of file aux_vis.cpp.
Referenced by Make_Texture_From_Palette(), and Make_Texture_From_Palette_2().
int MySetColorLogscale = 0
Definition at line 1150 of file aux_vis.cpp.
Referenced by VisualizationSceneScalarData::DrawColorBar(), and KeyLPressed().
int RepeatPaletteTimes = 1
Definition at line 1151 of file aux_vis.cpp.
Referenced by KeyF6Pressed().
double sph_t
Definition at line 414 of file aux_vis.cpp.
double sph_u
Definition at line 414 of file aux_vis.cpp.
double srot[16]
Definition at line 414 of file aux_vis.cpp.
GLfloat Texture_Image[3 *Max_Texture_Size]
Definition at line 1217 of file aux_vis.cpp.
int Texture_Size
Definition at line 1216 of file aux_vis.cpp.
Referenced by Make_Texture_From_Palette(), and Make_Texture_From_Palette_2().
int UseTexture = 0
Definition at line 1152 of file aux_vis.cpp.
Referenced by GetUseTexture().
int visualize = 0
Definition at line 29 of file aux_vis.cpp.
Referenced by KeyQPressed(), and ToggleThreads().
const double window_scale_factor = 1.1
Definition at line 1087 of file aux_vis.cpp.
double xang = 0.
Definition at line 413 of file aux_vis.cpp.
double yang = 0.
Definition at line 413 of file aux_vis.cpp.
Referenced by CheckSpin(), KeyDeletePressed(), LeftButtonUp(), and MainLoop().