GLVis: aux_vis.hpp File Reference
aux_vis.hpp File Reference
#include <GL/gl.h>
#include <GL/glu.h>
#include <GL/glx.h>
#include "tk.h"
#include "aux_gl.hpp"
#include "openglvis.hpp"
Functions
int InitVisualization (const char name[], int x, int y, int w, int h)
Initializes the visualization and some keys.
void SetVisualizationScene (VisualizationScene *scene, int view=3, char *keys=NULL)
Start the infinite visualization loop.
void KillVisualization ()
void SendExposeEvent ()
Send expose event. In our case MyReshape is executed and Draw after it.
void MyExpose ()
void MainLoop ()
void AddIdleFunc (void(*Func)(void))
void RemoveIdleFunc (void(*Func)(void))
void LeftButtonDown (AUX_EVENTREC *event)
void LeftButtonLoc (AUX_EVENTREC *event)
void LeftButtonUp (AUX_EVENTREC *event)
void MiddleButtonDown (AUX_EVENTREC *event)
void MiddleButtonLoc (AUX_EVENTREC *event)
void MiddleButtonUp (AUX_EVENTREC *event)
void RightButtonDown (AUX_EVENTREC *event)
void RightButtonLoc (AUX_EVENTREC *event)
void RightButtonUp (AUX_EVENTREC *event)
void KeyP ()
void KeyS ()
void KeyQPressed ()
void ToggleThreads ()
void Key1Pressed ()
void Key2Pressed ()
void Key3Pressed ()
void Key4Pressed ()
void Key5Pressed ()
void Key6Pressed ()
void Key7Pressed ()
void Key8Pressed ()
void Key9Pressed ()
void Key0Pressed ()
void KeyDeletePressed ()
void KeyEnterPressed ()
void KeyLeftPressed (GLenum)
void KeyRightPressed (GLenum)
void KeyUpPressed (GLenum)
void KeyDownPressed (GLenum)
void KeyJPressed ()
void KeyMinusPressed ()
void KeyPlusPressed ()
void ZoomIn ()
void ZoomOut ()
void ScaleUp ()
void ScaleDown ()
void LookAt ()
void ShrinkWindow ()
void EnlargeWindow ()
void MoveResizeWindow (int x, int y, int w, int h)
int Screenshot (const char *fname)
Take a screenshot using libtiff or xwd.
void SendKeySequence (char *seq)
Send a sequence of keystrokes to the visualization window.
void Cone ()
void MySetColor (double val, double min, double max)
void MySetColor (double val)
void SetUseTexture (int ut)
int GetUseTexture ()
Variables
float MatAlpha
float MatAlphaCenter
int MySetColorLogscale
Function Documentation
void AddIdleFunc (void(*)(void) Func)
Definition at line 399 of file aux_vis.cpp.
References IdleFuncs, and MainIdleFunc().
Referenced by CheckSpin(), KeyDeletePressed(), LeftButtonUp(), ScriptControl(), and SetVisualizationScene().
void Cone ()
Definition at line 1124 of file aux_vis.cpp.
Referenced by VisualizationSceneScalarData::Arrow2(), and VisualizationSceneScalarData::Arrow3().
void EnlargeWindow ()
Definition at line 1103 of file aux_vis.cpp.
Referenced by InitVisualization().
int GetUseTexture ()
Definition at line 1302 of file aux_vis.cpp.
References UseTexture.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), VisualizationSceneSolution::Draw(), VisualizationSceneScalarData::DrawColorBar(), KeyF6Pressed(), KeyPPressed(), and VisualizationSceneScalarData::ToggleTexture().
int InitVisualization (const char name[], int x, int y, int w, int h)
Initializes the visualization and some keys.
Definition at line 37 of file aux_vis.cpp.
References EnlargeWindow(), fontbase, Init_Palettes(), Key0Pressed(), Key1Pressed(), Key2Pressed(), Key3Pressed(), Key4Pressed(), Key5Pressed(), Key6Pressed(), Key7Pressed(), Key8Pressed(), Key9Pressed(), KeyDeletePressed(), KeyDownPressed(), KeyEnterPressed(), KeyJPressed(), KeyLeftPressed(), KeyMinusPressed(), KeyP(), KeyPlusPressed(), KeyQPressed(), KeyRightPressed(), KeyS(), KeyUpPressed(), LeftButtonDown(), LeftButtonLoc(), LeftButtonUp(), LookAt(), MiddleButtonDown(), MiddleButtonLoc(), MiddleButtonUp(), MyExpose(), RightButtonDown(), RightButtonLoc(), RightButtonUp(), ScaleDown(), ScaleUp(), Set_Texture_Image(), SetUseTexture(), ShrinkWindow(), ZoomIn(), and ZoomOut().
Referenced by InitVis().
void Key0Pressed ()
Definition at line 863 of file aux_vis.cpp.
References CheckSpin().
Referenced by InitVisualization().
void Key1Pressed ()
Definition at line 948 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key2Pressed ()
Definition at line 957 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key3Pressed ()
Definition at line 963 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key4Pressed ()
Definition at line 921 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key5Pressed ()
Definition at line 930 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key6Pressed ()
Definition at line 939 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key7Pressed ()
Definition at line 897 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key8Pressed ()
Definition at line 906 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void Key9Pressed ()
Definition at line 912 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyDeletePressed ()
Definition at line 871 of file aux_vis.cpp.
References AddIdleFunc(), MainLoop(), RemoveIdleFunc(), and yang.
Referenced by InitVisualization().
void KeyDownPressed (GLenum)
Definition at line 1022 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KeyEnterPressed ()
Definition at line 889 of file aux_vis.cpp.
References CheckSpin().
Referenced by InitVisualization().
void KeyJPressed ()
Definition at line 1035 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyLeftPressed (GLenum)
Definition at line 983 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KeyMinusPressed ()
Definition at line 1041 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyP ()
Definition at line 789 of file aux_vis.cpp.
Referenced by InitVisualization().
void KeyPlusPressed ()
Definition at line 1047 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void KeyQPressed ()
Definition at line 832 of file aux_vis.cpp.
References visualize.
Referenced by InitVisualization().
void KeyRightPressed (GLenum)
Definition at line 996 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KeyS ()
Definition at line 766 of file aux_vis.cpp.
References Screenshot().
Referenced by InitVisualization().
void KeyUpPressed (GLenum)
Definition at line 1009 of file aux_vis.cpp.
References VisualizationScene::Rotate(), SendExposeEvent(), and ShiftView().
Referenced by InitVisualization().
void KillVisualization ()
Definition at line 310 of file aux_vis.cpp.
References fontbase, and locscene.
Referenced by main(), and StartVisualization().
void LeftButtonDown (AUX_EVENTREC * event)
Definition at line 484 of file aux_vis.cpp.
References ComputeSphereAngles(), MainLoop(), RemoveIdleFunc(), and VisualizationScene::rotmat.
Referenced by InitVisualization().
void LeftButtonLoc (AUX_EVENTREC * event)
Definition at line 501 of file aux_vis.cpp.
References ComputeSphereAngles(), VisualizationScene::rotmat, and SendExposeEvent().
Referenced by InitVisualization().
void LeftButtonUp (AUX_EVENTREC * event)
Definition at line 572 of file aux_vis.cpp.
References AddIdleFunc(), MainLoop(), and yang.
Referenced by InitVisualization().
void LookAt ()
Definition at line 1077 of file aux_vis.cpp.
References SendExposeEvent(), VisualizationScene::ViewCenterX, and VisualizationScene::ViewCenterY.
Referenced by InitVisualization().
void MainLoop ()
Definition at line 420 of file aux_vis.cpp.
References Screenshot(), and yang.
Referenced by CheckSpin(), KeyDeletePressed(), KeyrPressed(), KeyRPressed(), LeftButtonDown(), LeftButtonUp(), and SetVisualizationScene().
void MiddleButtonDown (AUX_EVENTREC * event)
Definition at line 594 of file aux_vis.cpp.
Referenced by InitVisualization().
void MiddleButtonLoc (AUX_EVENTREC * event)
Definition at line 600 of file aux_vis.cpp.
References VisualizationScene::OrthogonalProjection, SendExposeEvent(), VisualizationScene::ViewAngle, VisualizationScene::ViewCenterX, VisualizationScene::ViewCenterY, and VisualizationScene::ViewScale.
Referenced by InitVisualization().
void MiddleButtonUp (AUX_EVENTREC * event)
Definition at line 633 of file aux_vis.cpp.
Referenced by InitVisualization().
void MoveResizeWindow (int x, int y, int w, int h)
Definition at line 1117 of file aux_vis.cpp.
Referenced by ExecuteScriptCommand().
void MyExpose ()
Definition at line 373 of file aux_vis.cpp.
References MyExpose().
void MySetColor (double val, double min, double max)
Definition at line 1154 of file aux_vis.cpp.
References MySetColor().
Referenced by VisualizationSceneSolution3d::CuttingPlaneFunc(), VisualizationSceneScalarData::DrawColorBar(), DrawPatch(), DrawQuad(), VisualizationSceneSolution3d::DrawRefinedSurf(), DrawTriangle(), VisualizationSceneVector::DrawVector(), VisualizationSceneVector3d::DrawVector(), MySetColor(), VisualizationSceneVector3d::Prepare(), VisualizationSceneSolution3d::Prepare(), VisualizationSceneSolution::Prepare(), VisualizationSceneVector3d::PrepareCuttingPlane(), and VisualizationSceneSolution3d::PrepareLevelSurf().
void MySetColor (double val)
Definition at line 1169 of file aux_vis.cpp.
References MatAlpha, MatAlphaCenter, RGB_Palette, and RGB_Palette_Size.
void RemoveIdleFunc (void(*)(void) Func)
Definition at line 405 of file aux_vis.cpp.
References IdleFuncs.
Referenced by CheckSpin(), KeyDeletePressed(), KeyrPressed(), KeyRPressed(), LeftButtonDown(), and ScriptControl().
void RightButtonDown (AUX_EVENTREC * event)
Definition at line 636 of file aux_vis.cpp.
Referenced by InitVisualization().
void RightButtonLoc (AUX_EVENTREC * event)
Definition at line 642 of file aux_vis.cpp.
References SendExposeEvent().
Referenced by InitVisualization().
void RightButtonUp (AUX_EVENTREC * event)
Definition at line 685 of file aux_vis.cpp.
Referenced by InitVisualization().
void ScaleDown ()
Definition at line 1071 of file aux_vis.cpp.
References VisualizationScene::Scale(), and SendExposeEvent().
Referenced by InitVisualization().
void ScaleUp ()
Definition at line 1065 of file aux_vis.cpp.
References VisualizationScene::Scale(), and SendExposeEvent().
Referenced by InitVisualization().
int Screenshot (const char * fname)
Take a screenshot using libtiff or xwd.
Definition at line 688 of file aux_vis.cpp.
Referenced by ExecuteScriptCommand(), KeyS(), and MainLoop().
void SendExposeEvent ()
Send expose event. In our case MyReshape is executed and Draw after it.
Definition at line 321 of file aux_vis.cpp.
Referenced by Key1Pressed(), Key2Pressed(), Key3Pressed(), Key4Pressed(), Key5Pressed(), Key6Pressed(), Key7Pressed(), Key8Pressed(), Key9Pressed(), KeyaPressed(), KeyAPressed(), KeyBackslashPressed(), KeyCommaPressed(), KeyCPressed(), KeyDownPressed(), KeyDPressed(), KeyF2Pressed(), KeyF6Pressed(), KeyF7Pressed(), KeyGPressed(), KeyGravePressed(), KeyiPressed(), KeyJPressed(), KeykPressed(), KeyKPressed(), KeyLeftPressed(), KeyLessPressed(), KeylPressed(), KeyLPressed(), KeyMinusPressed(), KeyPlusPressed(), KeyPPressed(), KeyRightPressed(), KeyrPressed(), KeyRPressed(), KeySPressed(), KeyTildePressed(), KeyToggleTexture(), KeyTPressed(), KeyUpPressed(), KeyuPressed(), KeyvPressed(), KeyVPressed(), LeftButtonLoc(), LookAt(), MiddleButtonLoc(), VisualizationSceneVector3d::NPressed(), VisualizationSceneVector::NPressed(), RightButtonLoc(), ScaleDown(), ScaleUp(), SendKeySequence(), ZoomIn(), and ZoomOut().
void SendKeySequence (char * seq)
Send a sequence of keystrokes to the visualization window.
Definition at line 187 of file aux_vis.cpp.
References SendExposeEvent(), and SendKeyEvent().
Referenced by ExecuteScriptCommand(), and SetVisualizationScene().
void SetUseTexture (int ut)
Definition at line 1307 of file aux_vis.cpp.
References Set_Texture_Image().
Referenced by VisualizationSceneSolution::Init(), VisualizationSceneSolution3d::Init(), InitVisualization(), and VisualizationSceneScalarData::ToggleTexture().
void SetVisualizationScene (VisualizationScene * scene, int view = 3, char * keys = NULL)
Start the infinite visualization loop.
Definition at line 288 of file aux_vis.cpp.
References AddIdleFunc(), InitIdleFuncs(), MainLoop(), and SendKeySequence().
Referenced by main(), and StartVisualization().
void ShrinkWindow ()
Definition at line 1089 of file aux_vis.cpp.
Referenced by InitVisualization().
void ToggleThreads ()
Definition at line 837 of file aux_vis.cpp.
References visualize.
Referenced by StartVisualization().
void ZoomIn ()
Definition at line 1053 of file aux_vis.cpp.
References SendExposeEvent(), and VisualizationScene::Zoom().
Referenced by InitVisualization().
void ZoomOut ()
Definition at line 1059 of file aux_vis.cpp.
References SendExposeEvent(), and VisualizationScene::Zoom().
Referenced by InitVisualization().
Variable Documentation
float MatAlpha
Definition at line 32 of file aux_vis.cpp.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), VisualizationSceneSolution::Draw(), KeykPressed(), KeyKPressed(), and MySetColor().
float MatAlphaCenter
Definition at line 33 of file aux_vis.cpp.
Referenced by KeyCommaPressed(), KeyLessPressed(), and MySetColor().
int MySetColorLogscale
Definition at line 1150 of file aux_vis.cpp.
Referenced by VisualizationSceneScalarData::DrawColorBar(), and KeyLPressed().