GLVis: VisualizationSceneVector3d Class Reference
VisualizationSceneVector3d Class Reference
#include <vsvector3d.hpp>
Public Member Functions
VisualizationSceneVector3d (Mesh &m, Vector &sx, Vector &sy, Vector &sz)
VisualizationSceneVector3d (GridFunction &vgf)
virtual ~VisualizationSceneVector3d ()
void NPressed ()
virtual void PrepareFlat ()
virtual void Prepare ()
virtual void PrepareLines ()
void PrepareFlat2 ()
void PrepareLines2 ()
void DrawVector (int type, double v0, double v1, double v2, double sx, double sy, double sz, double s)
virtual void PrepareVectorField ()
void PrepareDisplacedMesh ()
void ToggleVectorField (int i)
void SetScalarFunction ()
void ToggleScalarFunction ()
virtual void PrepareCuttingPlane ()
void ToggleDisplacements ()
virtual void Draw ()
virtual void EventUpdateColors ()
void ToggleVectorFieldLevel (int v)
void AddVectorFieldLevel ()
void RemoveVectorFieldLevel ()
Public Attributes
int ianim
int ianimd
int ianimmax
int drawdisp
Protected Member Functions
void Init ()
Protected Attributes
Vector * solx
Vector * soly
Vector * solz
int vectorlist
int displinelist
int drawvector
int scal_func
GridFunction * VecGridF
FiniteElementSpace * sfes
Array< int > vflevel
Array< double > dvflevel
Detailed Description
Definition at line 15 of file vsvector3d.hpp.
Constructor & Destructor Documentation
VisualizationSceneVector3d::VisualizationSceneVector3d (Mesh & m, Vector & sx, Vector & sy, Vector & sz)
Definition at line 316 of file vsvector3d.cpp.
References Init(), VisualizationSceneScalarData::mesh, sfes, VisualizationSceneScalarData::sol, solx, soly, solz, and VecGridF.
VisualizationSceneVector3d::VisualizationSceneVector3d (GridFunction & vgf)
Definition at line 332 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::GridF, Init(), VisualizationSceneScalarData::mesh, sfes, VisualizationSceneScalarData::sol, solx, soly, solz, and VecGridF.
VisualizationSceneVector3d::~VisualizationSceneVector3d () [virtual]
Definition at line 420 of file vsvector3d.cpp.
References displinelist, VisualizationSceneSolution3d::GridF, sfes, VisualizationSceneScalarData::sol, solx, soly, solz, VecGridF, and vectorlist.
Member Function Documentation
void VisualizationSceneVector3d::AddVectorFieldLevel ()
Definition at line 204 of file vsvector3d.cpp.
References dvflevel, VisualizationSceneScalarData::level, VisualizationSceneScalarData::nl, PrepareVectorField(), and vflevel.
void VisualizationSceneVector3d::Draw () [virtual]
Reimplemented from VisualizationSceneSolution3d.
Definition at line 1251 of file vsvector3d.cpp.
References VisualizationSceneScalarData::axeslist, VisualizationSceneScalarData::colorbar, VisualizationSceneSolution3d::cp_drawelems, VisualizationSceneSolution3d::cp_drawmesh, VisualizationSceneSolution3d::cplane, VisualizationSceneSolution3d::cplanelineslist, VisualizationSceneSolution3d::cplanelist, VisualizationSceneScalarData::CuttingPlane, displinelist, VisualizationSceneSolution3d::displlist, VisualizationSceneScalarData::drawaxes, VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawCoordinateCross(), drawdisp, VisualizationSceneSolution3d::drawelems, VisualizationSceneSolution3d::drawmesh, VisualizationSceneScalarData::DrawRuler(), drawvector, dvflevel, Plane::Equation(), GetUseTexture(), VisualizationSceneScalarData::level, VisualizationSceneScalarData::light, VisualizationSceneSolution3d::linelist, MatAlpha, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, Remove_Transparency(), VisualizationScene::rotmat, Set_Background(), Set_Black_Material(), Set_Transparency(), VisualizationScene::translmat, vectorlist, VisualizationScene::x, VisualizationScene::xscale, VisualizationScene::y, VisualizationScene::yscale, VisualizationScene::z, and VisualizationScene::zscale.
void VisualizationSceneVector3d::DrawVector (int type, double v0, double v1, double v2, double sx, double sy, double sz, double s)
Definition at line 969 of file vsvector3d.cpp.
References VisualizationSceneScalarData::Arrow(), VisualizationSceneScalarData::arrow_scaling_type, VisualizationSceneScalarData::arrow_type, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by PrepareCuttingPlane(), and PrepareVectorField().
virtual void VisualizationSceneVector3d::EventUpdateColors () [inline, virtual]
Reimplemented from VisualizationSceneSolution3d.
Definition at line 61 of file vsvector3d.hpp.
References Prepare(), PrepareCuttingPlane(), and PrepareVectorField().
void VisualizationSceneVector3d::Init () [protected]
Reimplemented from VisualizationSceneSolution3d.
Definition at line 361 of file vsvector3d.cpp.
References displinelist, drawdisp, drawvector, dvflevel, ianim, ianimd, ianimmax, VisualizationSceneScalarData::key_r_state, KeyBPressed(), KeyDPressed(), KeyNPressed(), KeyRPressed(), KeyrPressed(), KeyUPressed(), KeyuPressed(), KeyVPressed(), KeyvPressed(), VisualizationSceneScalarData::level, PrepareDisplacedMesh(), PrepareVectorField(), scal_func, SetScalarFunction(), vectorlist, and vflevel.
Referenced by VisualizationSceneVector3d().
void VisualizationSceneVector3d::NPressed ()
Definition at line 154 of file vsvector3d.cpp.
References drawdisp, Prepare(), PrepareDisplacedMesh(), PrepareLines(), and SendExposeEvent().
void VisualizationSceneVector3d::Prepare () [virtual]
Reimplemented from VisualizationSceneSolution3d.
Definition at line 595 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::bdr_attr_to_show, Compute3DUnitNormal(), VisualizationSceneSolution3d::displlist, ianim, ianimmax, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), PrepareFlat(), PrepareFlat2(), Set_Material(), VisualizationSceneSolution3d::shading, and VisualizationSceneScalarData::sol.
Referenced by EventUpdateColors(), and NPressed().
void VisualizationSceneVector3d::PrepareCuttingPlane () [virtual]
Reimplemented from VisualizationSceneSolution3d.
Definition at line 1118 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::cp_drawelems, VisualizationSceneSolution3d::cplane, VisualizationSceneSolution3d::cplanelist, VisualizationSceneScalarData::CuttingPlane, DrawVector(), drawvector, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), VisualizationSceneSolution3d::node_pos, VisualizationSceneSolution3d::PrepareCuttingPlane2(), Set_Material(), VisualizationSceneScalarData::sol, solx, soly, and solz.
Referenced by EventUpdateColors().
void VisualizationSceneVector3d::PrepareDisplacedMesh ()
Definition at line 879 of file vsvector3d.cpp.
References displinelist, ianimd, ianimmax, VisualizationSceneScalarData::mesh, and Set_Material().
Referenced by Init(), and NPressed().
void VisualizationSceneVector3d::PrepareFlat () [virtual]
Reimplemented from VisualizationSceneSolution3d.
Definition at line 437 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::bdr_attr_to_show, VisualizationSceneSolution3d::displlist, DrawQuad(), DrawTriangle(), ianim, ianimmax, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, and Set_Material().
Referenced by Prepare().
void VisualizationSceneVector3d::PrepareFlat2 ()
Reimplemented from VisualizationSceneSolution3d.
Definition at line 480 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::bdr_attr_to_show, VisualizationSceneSolution3d::cplane, VisualizationSceneSolution3d::displlist, DrawPatch(), VisualizationSceneSolution3d::FaceShiftScale, VisualizationSceneSolution3d::GetFaceNormals(), VisualizationSceneSolution3d::GridF, ianim, ianimmax, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, VisualizationSceneSolution3d::node_pos, Normalize(), Set_Material(), VisualizationSceneScalarData::ShrinkPoints(), VisualizationSceneSolution3d::TimesToRefine, VecGridF, VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by Prepare().
void VisualizationSceneVector3d::PrepareLines () [virtual]
Reimplemented from VisualizationSceneSolution3d.
Definition at line 694 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::bdr_attr_to_show, VisualizationSceneSolution3d::drawmesh, ianim, ianimmax, VisualizationSceneSolution3d::linelist, VisualizationSceneScalarData::mesh, PrepareLines2(), and VisualizationSceneSolution3d::shading.
Referenced by NPressed().
void VisualizationSceneVector3d::PrepareLines2 ()
Reimplemented from VisualizationSceneSolution3d.
Definition at line 742 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::bdr_attr_to_show, Compute3DUnitNormal(), VisualizationSceneSolution3d::cplane, VisualizationSceneSolution3d::drawmesh, VisualizationSceneScalarData::DrawPolygonLevelLines(), VisualizationSceneSolution3d::FaceShiftScale, VisualizationSceneSolution3d::GridF, ianim, ianimmax, VisualizationSceneScalarData::level, VisualizationSceneSolution3d::linelist, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, VisualizationSceneSolution3d::node_pos, VisualizationSceneScalarData::ShrinkPoints(), VisualizationSceneSolution3d::TimesToRefine, VecGridF, VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by PrepareLines().
void VisualizationSceneVector3d::PrepareVectorField () [virtual]
Definition at line 1019 of file vsvector3d.cpp.
References VisualizationSceneScalarData::arrow_scaling_type, VisualizationSceneScalarData::arrow_type, ArrowDrawOrNot(), ArrowsDrawOrNot(), VisualizationSceneSolution3d::drawmesh, DrawVector(), drawvector, VisualizationSceneScalarData::level, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::nl, Set_Material(), VisualizationSceneScalarData::sol, solx, soly, solz, vectorlist, and vflevel.
Referenced by AddVectorFieldLevel(), EventUpdateColors(), Init(), RemoveVectorFieldLevel(), ToggleVectorField(), and ToggleVectorFieldLevel().
void VisualizationSceneVector3d::RemoveVectorFieldLevel ()
Definition at line 213 of file vsvector3d.cpp.
References dvflevel, PrepareVectorField(), and vflevel.
void VisualizationSceneVector3d::SetScalarFunction ()
Definition at line 247 of file vsvector3d.cpp.
References VisualizationSceneSolution3d::GridF, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, scal_func, VisualizationSceneScalarData::sol, solx, soly, solz, VecGridF, VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by Init(), and ToggleScalarFunction().
void VisualizationSceneVector3d::ToggleDisplacements () [inline]
Definition at line 57 of file vsvector3d.hpp.
References drawdisp.
void VisualizationSceneVector3d::ToggleScalarFunction ()
Definition at line 306 of file vsvector3d.cpp.
References scal_func, SetScalarFunction(), and VisualizationSceneSolution3d::UpdateValueRange().
void VisualizationSceneVector3d::ToggleVectorField (int i)
Definition at line 238 of file vsvector3d.cpp.
References drawvector, and PrepareVectorField().
void VisualizationSceneVector3d::ToggleVectorFieldLevel (int v)
Definition at line 179 of file vsvector3d.cpp.
References dvflevel, VisualizationSceneScalarData::level, VisualizationSceneScalarData::nl, PrepareVectorField(), and vflevel.
Member Data Documentation
int VisualizationSceneVector3d::displinelist [protected]
Definition at line 20 of file vsvector3d.hpp.
Referenced by Draw(), Init(), PrepareDisplacedMesh(), and ~VisualizationSceneVector3d().
int VisualizationSceneVector3d::drawdisp
Definition at line 31 of file vsvector3d.hpp.
Referenced by Draw(), Init(), NPressed(), and ToggleDisplacements().
int VisualizationSceneVector3d::drawvector [protected]
Definition at line 20 of file vsvector3d.hpp.
Referenced by Draw(), Init(), PrepareCuttingPlane(), PrepareVectorField(), and ToggleVectorField().
Array<double> VisualizationSceneVector3d::dvflevel [protected]
Definition at line 28 of file vsvector3d.hpp.
Referenced by AddVectorFieldLevel(), Draw(), Init(), RemoveVectorFieldLevel(), and ToggleVectorFieldLevel().
int VisualizationSceneVector3d::ianim
Definition at line 31 of file vsvector3d.hpp.
Referenced by Init(), Prepare(), PrepareFlat(), PrepareFlat2(), PrepareLines(), and PrepareLines2().
int VisualizationSceneVector3d::ianimd
Definition at line 31 of file vsvector3d.hpp.
Referenced by Init(), and PrepareDisplacedMesh().
int VisualizationSceneVector3d::ianimmax
Definition at line 31 of file vsvector3d.hpp.
Referenced by Init(), Prepare(), PrepareDisplacedMesh(), PrepareFlat(), PrepareFlat2(), PrepareLines(), and PrepareLines2().
int VisualizationSceneVector3d::scal_func [protected]
Definition at line 20 of file vsvector3d.hpp.
Referenced by Init(), SetScalarFunction(), and ToggleScalarFunction().
FiniteElementSpace* VisualizationSceneVector3d::sfes [protected]
Definition at line 23 of file vsvector3d.hpp.
Referenced by VisualizationSceneVector3d(), and ~VisualizationSceneVector3d().
Vector* VisualizationSceneVector3d::solx [protected]
Definition at line 19 of file vsvector3d.hpp.
Referenced by PrepareCuttingPlane(), PrepareVectorField(), SetScalarFunction(), VisualizationSceneVector3d(), and ~VisualizationSceneVector3d().
Vector * VisualizationSceneVector3d::soly [protected]
Definition at line 19 of file vsvector3d.hpp.
Referenced by PrepareCuttingPlane(), PrepareVectorField(), SetScalarFunction(), VisualizationSceneVector3d(), and ~VisualizationSceneVector3d().
Vector * VisualizationSceneVector3d::solz [protected]
Definition at line 19 of file vsvector3d.hpp.
Referenced by PrepareCuttingPlane(), PrepareVectorField(), SetScalarFunction(), VisualizationSceneVector3d(), and ~VisualizationSceneVector3d().
GridFunction* VisualizationSceneVector3d::VecGridF [protected]
Definition at line 22 of file vsvector3d.hpp.
Referenced by PrepareFlat2(), PrepareLines2(), SetScalarFunction(), VisualizationSceneVector3d(), and ~VisualizationSceneVector3d().
int VisualizationSceneVector3d::vectorlist [protected]
Definition at line 20 of file vsvector3d.hpp.
Referenced by Draw(), Init(), PrepareVectorField(), and ~VisualizationSceneVector3d().
Array<int> VisualizationSceneVector3d::vflevel [protected]
Definition at line 27 of file vsvector3d.hpp.
Referenced by AddVectorFieldLevel(), Init(), PrepareVectorField(), RemoveVectorFieldLevel(), and ToggleVectorFieldLevel().
The documentation for this class was generated from the following files:
vsvector3d.hpp
vsvector3d.cpp