GLVis: VisualizationSceneVector Class Reference
VisualizationSceneVector Class Reference
#include <vsvector.hpp>
Public Member Functions
VisualizationSceneVector (Mesh &m, Vector &sx, Vector &sy)
VisualizationSceneVector (GridFunction &vgf)
void NewMeshAndSolution (GridFunction &vgf, int rescale=0)
virtual ~VisualizationSceneVector ()
void NPressed ()
void PrepareDisplacedMesh ()
virtual void PrepareLines ()
virtual void PrepareVectorField ()
void ToggleVectorField ()
void ToggleDisplacements ()
virtual void Draw ()
virtual void EventUpdateColors ()
void CycleVec2Scalar (int print=0)
Public Attributes
int RefineFactor
double ArrowScale
Protected Member Functions
void Init ()
virtual void GetRefinedValues (int i, const IntegrationRule &ir, Vector &vals, DenseMatrix &tr)
virtual int GetRefinedValuesAndNormals (int i, const IntegrationRule &ir, Vector &vals, DenseMatrix &tr, DenseMatrix &normals)
void DrawVector (double, double, double, double, double)
Protected Attributes
Vector * solx
Vector * soly
int vectorlist
int displinelist
int drawdisp
int drawvector
GridFunction * VecGridF
double(* Vec2Scalar)(double, double)
double maxlen
Vector vc0
IsoparametricTransformation T0
Detailed Description
Definition at line 15 of file vsvector.hpp.
Constructor & Destructor Documentation
VisualizationSceneVector::VisualizationSceneVector (Mesh & m, Vector & sx, Vector & sy)
Definition at line 212 of file vsvector.cpp.
References Init(), VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::sol, solx, soly, and VecGridF.
VisualizationSceneVector::VisualizationSceneVector (GridFunction & vgf)
Definition at line 226 of file vsvector.cpp.
References Init(), VisualizationSceneScalarData::mesh, VisualizationSceneSolution::SetGridFunction(), VisualizationSceneScalarData::sol, solx, soly, vc0, and VecGridF.
VisualizationSceneVector::~VisualizationSceneVector () [virtual]
Definition at line 434 of file vsvector.cpp.
References displinelist, VisualizationSceneScalarData::sol, solx, soly, VecGridF, and vectorlist.
Member Function Documentation
void VisualizationSceneVector::CycleVec2Scalar (int print = 0)
Definition at line 303 of file vsvector.cpp.
References VisualizationSceneSolution::DefaultLevelLines(), drawvector, VisualizationSceneSolution::FindNewBox(), maxlen, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneSolution::Prepare(), VisualizationSceneScalarData::PrepareAxes(), VisualizationSceneSolution::PrepareCP(), VisualizationSceneSolution::PrepareLevelCurves(), PrepareLines(), PrepareVectorField(), VisualizationSceneScalarData::sol, solx, soly, Vec2Scalar, Vec2ScalarFunctions, Vec2ScalarNames, and VecGridF.
Referenced by KeyuPressed().
void VisualizationSceneVector::Draw () [virtual]
Reimplemented from VisualizationSceneSolution.
Definition at line 852 of file vsvector.cpp.
References VisualizationSceneScalarData::axeslist, VisualizationSceneScalarData::colorbar, VisualizationSceneSolution::cp_list, VisualizationSceneScalarData::CuttingPlane, displinelist, VisualizationSceneSolution::displlist, VisualizationSceneSolution::draw_cp, VisualizationSceneScalarData::drawaxes, VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawCoordinateCross(), drawdisp, VisualizationSceneSolution::drawelems, VisualizationSceneSolution::drawmesh, VisualizationSceneScalarData::DrawRuler(), drawvector, Plane::Equation(), GetUseTexture(), VisualizationSceneSolution::lcurvelist, VisualizationSceneScalarData::level, VisualizationSceneScalarData::light, VisualizationSceneSolution::linelist, MatAlpha, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, Remove_Transparency(), VisualizationScene::rotmat, Set_Background(), Set_Black_Material(), Set_Transparency(), VisualizationScene::translmat, vectorlist, VisualizationScene::x, VisualizationScene::xscale, VisualizationScene::y, VisualizationScene::yscale, VisualizationScene::z, and VisualizationScene::zscale.
void VisualizationSceneVector::DrawVector (double px, double py, double vx, double vy, double cval) [protected]
Definition at line 751 of file vsvector.cpp.
References VisualizationSceneScalarData::Arrow(), VisualizationSceneScalarData::arrow_scaling_type, VisualizationSceneScalarData::arrow_type, ArrowScale, drawvector, maxlen, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), new_maxlen, VecLength(), VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by PrepareVectorField().
virtual void VisualizationSceneVector::EventUpdateColors () [inline, virtual]
Reimplemented from VisualizationSceneScalarData.
Definition at line 66 of file vsvector.hpp.
References VisualizationSceneSolution::Prepare(), and PrepareVectorField().
void VisualizationSceneVector::GetRefinedValues (int i, const IntegrationRule & ir, Vector & vals, DenseMatrix & tr) [protected, virtual]
Reimplemented from VisualizationSceneSolution.
Definition at line 448 of file vsvector.cpp.
References VisualizationSceneSolution::drawelems, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::shrink, VisualizationSceneScalarData::shrinkmat, VisualizationSceneScalarData::ShrinkPoints(), T0, vc0, Vec2Scalar, VecAnisotrSubst(), VecCurlSubst(), VecDivSubst(), and VecGridF.
Referenced by GetRefinedValuesAndNormals().
int VisualizationSceneVector::GetRefinedValuesAndNormals (int i, const IntegrationRule & ir, Vector & vals, DenseMatrix & tr, DenseMatrix & normals) [protected, virtual]
Reimplemented from VisualizationSceneSolution.
Definition at line 543 of file vsvector.cpp.
References GetRefinedValues().
void VisualizationSceneVector::Init () [protected]
Reimplemented from VisualizationSceneSolution.
Definition at line 389 of file vsvector.cpp.
References ArrowScale, displinelist, drawdisp, drawvector, KeyBPressed(), KeyDPressed(), KeyNPressed(), KeyuPressed(), KeyUPressed(), KeyvPressed(), KeyVPressed(), maxlen, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, PrepareVectorField(), RefineFactor, VisualizationSceneScalarData::sol, solx, soly, Vec2Scalar, VecLength(), and vectorlist.
Referenced by VisualizationSceneVector().
void VisualizationSceneVector::NewMeshAndSolution (GridFunction & vgf, int rescale = 0)
Definition at line 340 of file vsvector.cpp.
References maxlen, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, PrepareVectorField(), VisualizationSceneScalarData::sol, solx, soly, vc0, Vec2Scalar, VecGridF, and VecLength().
Referenced by GLVisCommand::Execute(), and ExecuteScriptCommand().
void VisualizationSceneVector::NPressed ()
Definition at line 115 of file vsvector.cpp.
References drawdisp, PrepareDisplacedMesh(), and SendExposeEvent().
void VisualizationSceneVector::PrepareDisplacedMesh ()
Definition at line 554 of file vsvector.cpp.
References displinelist, drawdisp, VisualizationSceneSolution::DrawLevelCurves(), VisualizationSceneSolution::EdgeRefineFactor, VisualizationSceneScalarData::level, VisualizationSceneScalarData::mesh, VisualizationSceneSolution::shading, VisualizationSceneSolution::TimesToRefine, VecGridF, VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by NPressed(), PrepareLines(), and ToggleDisplacements().
virtual void VisualizationSceneVector::PrepareLines () [inline, virtual]
Reimplemented from VisualizationSceneSolution.
Definition at line 51 of file vsvector.hpp.
References PrepareDisplacedMesh().
Referenced by CycleVec2Scalar().
void VisualizationSceneVector::PrepareVectorField () [virtual]
Definition at line 785 of file vsvector.cpp.
References drawvector, DrawVector(), maxlen, VisualizationSceneScalarData::mesh, new_maxlen, RefineFactor, VisualizationSceneSolution::shading, VisualizationSceneScalarData::sol, solx, soly, Vec2Scalar, VecGridF, and vectorlist.
Referenced by CycleVec2Scalar(), EventUpdateColors(), Init(), KeyuPressed(), NewMeshAndSolution(), and ToggleVectorField().
void VisualizationSceneVector::ToggleDisplacements () [inline]
Definition at line 57 of file vsvector.hpp.
References drawdisp, and PrepareDisplacedMesh().
void VisualizationSceneVector::ToggleVectorField ()
Definition at line 206 of file vsvector.cpp.
References drawvector, and PrepareVectorField().
Member Data Documentation
double VisualizationSceneVector::ArrowScale
Definition at line 70 of file vsvector.hpp.
Referenced by DrawVector(), and Init().
int VisualizationSceneVector::displinelist [protected]
Definition at line 20 of file vsvector.hpp.
Referenced by Draw(), Init(), PrepareDisplacedMesh(), and ~VisualizationSceneVector().
int VisualizationSceneVector::drawdisp [protected]
Definition at line 20 of file vsvector.hpp.
Referenced by Draw(), Init(), NPressed(), PrepareDisplacedMesh(), and ToggleDisplacements().
int VisualizationSceneVector::drawvector [protected]
Definition at line 20 of file vsvector.hpp.
Referenced by CycleVec2Scalar(), Draw(), DrawVector(), Init(), PrepareVectorField(), and ToggleVectorField().
double VisualizationSceneVector::maxlen [protected]
Definition at line 36 of file vsvector.hpp.
Referenced by CycleVec2Scalar(), DrawVector(), Init(), NewMeshAndSolution(), and PrepareVectorField().
int VisualizationSceneVector::RefineFactor
Definition at line 68 of file vsvector.hpp.
Referenced by Init(), KeyuPressed(), and PrepareVectorField().
Vector* VisualizationSceneVector::solx [protected]
Definition at line 19 of file vsvector.hpp.
Referenced by CycleVec2Scalar(), Init(), NewMeshAndSolution(), PrepareVectorField(), VisualizationSceneVector(), and ~VisualizationSceneVector().
Vector * VisualizationSceneVector::soly [protected]
Definition at line 19 of file vsvector.hpp.
Referenced by CycleVec2Scalar(), Init(), NewMeshAndSolution(), PrepareVectorField(), VisualizationSceneVector(), and ~VisualizationSceneVector().
IsoparametricTransformation VisualizationSceneVector::T0 [protected]
Definition at line 39 of file vsvector.hpp.
Referenced by GetRefinedValues().
Vector VisualizationSceneVector::vc0 [protected]
Definition at line 38 of file vsvector.hpp.
Referenced by GetRefinedValues(), NewMeshAndSolution(), and VisualizationSceneVector().
double(* VisualizationSceneVector::Vec2Scalar)(double, double) [protected]
Definition at line 32 of file vsvector.hpp.
Referenced by CycleVec2Scalar(), GetRefinedValues(), Init(), NewMeshAndSolution(), and PrepareVectorField().
GridFunction* VisualizationSceneVector::VecGridF [protected]
Definition at line 22 of file vsvector.hpp.
Referenced by CycleVec2Scalar(), GetRefinedValues(), NewMeshAndSolution(), PrepareDisplacedMesh(), PrepareVectorField(), VisualizationSceneVector(), and ~VisualizationSceneVector().
int VisualizationSceneVector::vectorlist [protected]
Definition at line 20 of file vsvector.hpp.
Referenced by Draw(), Init(), PrepareVectorField(), and ~VisualizationSceneVector().
The documentation for this class was generated from the following files:
vsvector.hpp
vsvector.cpp