GLVis: Plane Class Reference
Plane Class Reference
#include <vsdata.hpp>
Public Member Functions
Plane (double A, double B, double C, double D)
double * Equation ()
double Transform (double x, double y, double z)
double Transform (double *x)
void IncreasePhi ()
void DecreasePhi ()
void IncreaseTheta ()
void DecreaseTheta ()
void IncreaseDistance ()
void DecreaseDistance ()
Private Member Functions
void CartesianToSpherical ()
void SphericalToCartesian ()
Private Attributes
double eqn [4]
double phi
double theta
double rho
double x0
double y0
double z0
double bbox_diam
double phi_step
double theta_step
double rho_step
Detailed Description
Definition at line 19 of file vsdata.hpp.
Constructor & Destructor Documentation
Plane::Plane (double A, double B, double C, double D)
Definition at line 1388 of file vsdata.cpp.
References vsdata.
Member Function Documentation
void Plane::CartesianToSpherical () [private]
Definition at line 1413 of file vsdata.cpp.
void Plane::DecreaseDistance ()
Definition at line 1462 of file vsdata.cpp.
void Plane::DecreasePhi ()
Definition at line 1434 of file vsdata.cpp.
void Plane::DecreaseTheta ()
Definition at line 1446 of file vsdata.cpp.
double* Plane::Equation () [inline]
Definition at line 34 of file vsdata.hpp.
References eqn.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), and VisualizationSceneSolution::Draw().
void Plane::IncreaseDistance ()
Definition at line 1452 of file vsdata.cpp.
void Plane::IncreasePhi ()
Definition at line 1428 of file vsdata.cpp.
void Plane::IncreaseTheta ()
Definition at line 1440 of file vsdata.cpp.
void Plane::SphericalToCartesian () [private]
Definition at line 1420 of file vsdata.cpp.
double Plane::Transform (double x, double y, double z) [inline]
Definition at line 35 of file vsdata.hpp.
References eqn.
Referenced by VisualizationSceneSolution::DrawCPLine(), and VisualizationSceneSolution::PrepareCP().
double Plane::Transform (double * x) [inline]
Definition at line 37 of file vsdata.hpp.
References eqn.
Member Data Documentation
double Plane::bbox_diam [private]
Definition at line 28 of file vsdata.hpp.
double Plane::eqn[4] [private]
Definition at line 22 of file vsdata.hpp.
Referenced by Equation(), and Transform().
double Plane::phi [private]
Definition at line 23 of file vsdata.hpp.
double Plane::phi_step [private]
Definition at line 30 of file vsdata.hpp.
double Plane::rho [private]
Definition at line 23 of file vsdata.hpp.
double Plane::rho_step [private]
Definition at line 30 of file vsdata.hpp.
double Plane::theta [private]
Definition at line 23 of file vsdata.hpp.
double Plane::theta_step [private]
Definition at line 30 of file vsdata.hpp.
double Plane::x0 [private]
Definition at line 24 of file vsdata.hpp.
double Plane::y0 [private]
Definition at line 24 of file vsdata.hpp.
double Plane::z0 [private]
Definition at line 24 of file vsdata.hpp.
The documentation for this class was generated from the following files:
vsdata.hpp
vsdata.cpp