GLVis: VisualizationSceneSolution Class Reference
VisualizationSceneSolution Class Reference
#include <vssolution.hpp>
Public Member Functions
VisualizationSceneSolution ()
VisualizationSceneSolution (Mesh &m, Vector &s)
virtual ~VisualizationSceneSolution ()
void SetGridFunction (GridFunction &u)
void NewMeshAndSolution (Mesh *new_m, Vector *new_sol, GridFunction *new_u=NULL, int rescale=0)
virtual void SetNewScalingFromBox ()
virtual void FindNewBox ()
virtual void UpdateLevelLines ()
virtual void UpdateValueRange ()
void PrepareFlat ()
void PrepareFlat2 ()
virtual void PrepareLines ()
void PrepareLines2 ()
void PrepareLines3 ()
virtual void Prepare ()
void PrepareLevelCurves ()
void PrepareLevelCurves2 ()
void DefaultLevelLines ()
void PrepareBoundary ()
void PrepareCP ()
virtual void Draw ()
void ToggleDrawBdr ()
void ToggleDrawElems ()
void ToggleDrawMesh ()
virtual void SetShading (int)
void ToggleShading ()
void ToggleDrawCP ()
virtual void SetRefineFactors (int, int)
virtual void ToggleAttributes (Array< int > &attr_list)
Public Attributes
int shading
int TimesToRefine
int EdgeRefineFactor
int attr_to_show
Array< int > el_attr_to_show
Protected Member Functions
void Init ()
void FindNewBox (double rx[], double ry[], double rval[])
void FixValueRange ()
void NewZRange (double z1, double z2)
void DrawCPLine (DenseMatrix &pointmat, Vector &values, Array< int > &ind)
void GetRefinedDetJ (int i, const IntegrationRule &ir, Vector &vals, DenseMatrix &tr)
virtual void GetRefinedValues (int i, const IntegrationRule &ir, Vector &vals, DenseMatrix &tr)
virtual int GetRefinedValuesAndNormals (int i, const IntegrationRule &ir, Vector &vals, DenseMatrix &tr, DenseMatrix &normals)
void DrawLevelCurves (Array< int > &RG, DenseMatrix &pointmat, Vector &values, int sides, Array< double > &lvl, int flat=0)
Protected Attributes
GridFunction * rsol
int drawmesh
int drawelems
int displlist
int linelist
int lcurvelist
int bdrlist
int drawbdr
int draw_cp
int cp_list
Detailed Description
Definition at line 17 of file vssolution.hpp.
Constructor & Destructor Documentation
VisualizationSceneSolution::VisualizationSceneSolution ()
Definition at line 334 of file vssolution.cpp.
VisualizationSceneSolution::VisualizationSceneSolution (Mesh & m, Vector & s)
Definition at line 337 of file vssolution.cpp.
References Init(), VisualizationSceneScalarData::mesh, and VisualizationSceneScalarData::sol.
VisualizationSceneSolution::~VisualizationSceneSolution () [virtual]
Definition at line 424 of file vssolution.cpp.
References bdrlist, cp_list, displlist, lcurvelist, and linelist.
Member Function Documentation
void VisualizationSceneSolution::DefaultLevelLines () [inline]
Definition at line 80 of file vssolution.hpp.
References VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, and VisualizationSceneScalarData::SetLevelLines().
Referenced by VisualizationSceneVector::CycleVec2Scalar(), Init(), and ToggleDrawElems().
void VisualizationSceneSolution::Draw () [virtual]
Reimplemented from VisualizationScene.
Reimplemented in VisualizationSceneVector.
Definition at line 1581 of file vssolution.cpp.
References VisualizationSceneScalarData::axeslist, bdrlist, VisualizationSceneScalarData::colorbar, cp_list, VisualizationSceneScalarData::CuttingPlane, displlist, draw_cp, VisualizationSceneScalarData::drawaxes, drawbdr, VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawCoordinateCross(), drawelems, drawmesh, VisualizationSceneScalarData::DrawRuler(), Plane::Equation(), GetUseTexture(), lcurvelist, VisualizationSceneScalarData::level, VisualizationSceneScalarData::light, linelist, MatAlpha, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, Remove_Transparency(), VisualizationScene::rotmat, Set_Background(), Set_Black_Material(), Set_Transparency(), VisualizationScene::translmat, VisualizationScene::x, VisualizationScene::xscale, VisualizationScene::y, VisualizationScene::yscale, VisualizationScene::z, and VisualizationScene::zscale.
void VisualizationSceneSolution::DrawCPLine (DenseMatrix & pointmat, Vector & values, Array< int > & ind) [protected]
Definition at line 1544 of file vssolution.cpp.
References VisualizationSceneScalarData::CuttingPlane, and Plane::Transform().
Referenced by PrepareCP().
void VisualizationSceneSolution::DrawLevelCurves (Array< int > & RG, DenseMatrix & pointmat, Vector & values, int sides, Array< double > & lvl, int flat = 0) [protected]
Definition at line 1164 of file vssolution.cpp.
References VisualizationSceneScalarData::DrawPolygonLevelLines(), and VisualizationScene::z.
Referenced by VisualizationSceneVector::PrepareDisplacedMesh(), and PrepareLevelCurves2().
void VisualizationSceneSolution::FindNewBox (double rx[], double ry[], double rval[]) [protected]
Definition at line 681 of file vssolution.cpp.
References EdgeRefineFactor, GetRefinedValues(), VisualizationSceneScalarData::mesh, shading, VisualizationSceneScalarData::sol, and TimesToRefine.
void VisualizationSceneSolution::FindNewBox () [virtual]
Implements VisualizationSceneScalarData.
Definition at line 761 of file vssolution.cpp.
References FixValueRange(), VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, SetNewScalingFromBox(), VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by VisualizationSceneVector::CycleVec2Scalar(), NewMeshAndSolution(), ToggleDrawElems(), and ToggleShading().
void VisualizationSceneSolution::FixValueRange () [protected]
Definition at line 741 of file vssolution.cpp.
References VisualizationSceneScalarData::maxv, and VisualizationSceneScalarData::minv.
Referenced by FindNewBox(), and NewMeshAndSolution().
void VisualizationSceneSolution::GetRefinedDetJ (int i, const IntegrationRule & ir, Vector & vals, DenseMatrix & tr) [protected]
Definition at line 465 of file vssolution.cpp.
References drawelems, and VisualizationSceneScalarData::mesh.
Referenced by GetRefinedValues(), and GetRefinedValuesAndNormals().
void VisualizationSceneSolution::GetRefinedValues (int i, const IntegrationRule & ir, Vector & vals, DenseMatrix & tr) [protected, virtual]
Reimplemented in VisualizationSceneVector.
Definition at line 493 of file vssolution.cpp.
References drawelems, GetRefinedDetJ(), rsol, VisualizationSceneScalarData::shrink, VisualizationSceneScalarData::shrinkmat, and VisualizationSceneScalarData::ShrinkPoints().
Referenced by FindNewBox(), PrepareBoundary(), PrepareCP(), PrepareLevelCurves2(), PrepareLines2(), and PrepareLines3().
int VisualizationSceneSolution::GetRefinedValuesAndNormals (int i, const IntegrationRule & ir, Vector & vals, DenseMatrix & tr, DenseMatrix & normals) [protected, virtual]
Reimplemented in VisualizationSceneVector.
Definition at line 505 of file vssolution.cpp.
References drawelems, GetRefinedDetJ(), rsol, VisualizationSceneScalarData::shrink, VisualizationSceneScalarData::shrinkmat, and VisualizationSceneScalarData::ShrinkPoints().
Referenced by PrepareFlat2().
void VisualizationSceneSolution::Init () [protected]
Reimplemented from VisualizationSceneScalarData.
Reimplemented in VisualizationSceneVector.
Definition at line 348 of file vssolution.cpp.
References attr_to_show, VisualizationSceneScalarData::bdrc, bdrlist, cp_list, VisualizationSceneScalarData::CuttingPlane, DefaultLevelLines(), displlist, draw_cp, drawbdr, drawelems, drawmesh, EdgeRefineFactor, el_attr_to_show, KeyBPressed(), KeyiPressed(), KeyIPressed(), lcurvelist, linelist, VisualizationSceneScalarData::matc, VisualizationSceneScalarData::mesh, Prepare(), PrepareBoundary(), PrepareLevelCurves(), PrepareLines(), rsol, SetUseTexture(), shading, VisualizationSceneScalarData::shrink, VisualizationSceneScalarData::shrinkmat, TimesToRefine, and VisualizationScene::x.
Referenced by VisualizationSceneSolution().
void VisualizationSceneSolution::NewMeshAndSolution (Mesh * new_m, Vector * new_sol, GridFunction * new_u = NULL, int rescale = 0)
Definition at line 434 of file vssolution.cpp.
References FindNewBox(), FixValueRange(), VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, NewZRange(), Prepare(), VisualizationSceneScalarData::PrepareAxes(), PrepareBoundary(), PrepareCP(), PrepareLevelCurves(), PrepareLines(), rsol, and VisualizationSceneScalarData::sol.
Referenced by GLVisCommand::Execute(), and ExecuteScriptCommand().
void VisualizationSceneSolution::NewZRange (double z1, double z2) [protected]
Definition at line 646 of file vssolution.cpp.
References VisualizationScene::z, and VisualizationScene::zscale.
Referenced by NewMeshAndSolution(), and UpdateValueRange().
void VisualizationSceneSolution::Prepare () [virtual]
Reimplemented from VisualizationScene.
Definition at line 1039 of file vssolution.cpp.
References Compute3DUnitNormal(), displlist, el_attr_to_show, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), PrepareFlat(), PrepareFlat2(), Set_Material(), shading, and VisualizationSceneScalarData::sol.
Referenced by VisualizationSceneVector::CycleVec2Scalar(), VisualizationSceneVector::EventUpdateColors(), Init(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), ToggleAttributes(), ToggleDrawElems(), and ToggleShading().
void VisualizationSceneSolution::PrepareBoundary ()
Definition at line 1401 of file vssolution.cpp.
References bdrlist, EdgeRefineFactor, GetRefinedValues(), VisualizationSceneScalarData::mesh, shading, VisualizationSceneScalarData::shrink, and TimesToRefine.
Referenced by Init(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), ToggleDrawElems(), and ToggleShading().
void VisualizationSceneSolution::PrepareCP ()
Definition at line 1462 of file vssolution.cpp.
References cp_list, VisualizationSceneScalarData::CuttingPlane, draw_cp, DrawCPLine(), EdgeRefineFactor, GetRefinedValues(), VisualizationSceneScalarData::mesh, shading, TimesToRefine, and Plane::Transform().
Referenced by VisualizationSceneVector::CycleVec2Scalar(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), ToggleDrawCP(), ToggleDrawElems(), and ToggleShading().
void VisualizationSceneSolution::PrepareFlat ()
Definition at line 896 of file vssolution.cpp.
References displlist, DrawQuad(), DrawTriangle(), el_attr_to_show, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, and Set_Material().
Referenced by Prepare().
void VisualizationSceneSolution::PrepareFlat2 ()
Definition at line 938 of file vssolution.cpp.
References displlist, DrawPatch(), DrawQuad(), DrawTriangle(), EdgeRefineFactor, el_attr_to_show, GetRefinedValuesAndNormals(), VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, Set_Material(), and TimesToRefine.
Referenced by Prepare().
void VisualizationSceneSolution::PrepareLevelCurves ()
Definition at line 1133 of file vssolution.cpp.
References VisualizationSceneScalarData::DrawPolygonLevelLines(), lcurvelist, VisualizationSceneScalarData::level, VisualizationSceneScalarData::mesh, PrepareLevelCurves2(), and shading.
Referenced by VisualizationSceneVector::CycleVec2Scalar(), Init(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), ToggleDrawElems(), ToggleShading(), and UpdateLevelLines().
void VisualizationSceneSolution::PrepareLevelCurves2 ()
Definition at line 1241 of file vssolution.cpp.
References DrawLevelCurves(), EdgeRefineFactor, GetRefinedValues(), lcurvelist, VisualizationSceneScalarData::level, VisualizationSceneScalarData::mesh, and TimesToRefine.
Referenced by PrepareLevelCurves().
void VisualizationSceneSolution::PrepareLines () [virtual]
Implements VisualizationSceneScalarData.
Reimplemented in VisualizationSceneVector.
Definition at line 1264 of file vssolution.cpp.
References el_attr_to_show, linelist, VisualizationSceneScalarData::mesh, PrepareLines3(), and shading.
Referenced by Init(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), ToggleAttributes(), ToggleDrawElems(), and ToggleShading().
void VisualizationSceneSolution::PrepareLines2 ()
Definition at line 1308 of file vssolution.cpp.
References EdgeRefineFactor, el_attr_to_show, GetRefinedValues(), linelist, VisualizationSceneScalarData::mesh, and TimesToRefine.
void VisualizationSceneSolution::PrepareLines3 ()
Definition at line 1355 of file vssolution.cpp.
References EdgeRefineFactor, el_attr_to_show, GetRefinedValues(), linelist, VisualizationSceneScalarData::mesh, and TimesToRefine.
Referenced by PrepareLines().
void VisualizationSceneSolution::SetGridFunction (GridFunction & u) [inline]
Definition at line 59 of file vssolution.hpp.
References rsol.
Referenced by main(), StartVisualization(), and VisualizationSceneVector::VisualizationSceneVector().
void VisualizationSceneSolution::SetNewScalingFromBox () [virtual]
Reimplemented from VisualizationSceneScalarData.
Definition at line 654 of file vssolution.cpp.
References VisualizationSceneScalarData::scaling, VisualizationScene::x, VisualizationScene::xscale, VisualizationScene::y, VisualizationScene::yscale, VisualizationScene::z, and VisualizationScene::zscale.
Referenced by FindNewBox().
void VisualizationSceneSolution::SetRefineFactors (int tot, int bdr) [virtual]
Implements VisualizationSceneScalarData.
Definition at line 598 of file vssolution.cpp.
References EdgeRefineFactor, Prepare(), VisualizationSceneScalarData::PrepareAxes(), PrepareBoundary(), PrepareCP(), PrepareLevelCurves(), PrepareLines(), shading, and TimesToRefine.
void VisualizationSceneSolution::SetShading (int s) [virtual]
Implements VisualizationSceneScalarData.
Definition at line 543 of file vssolution.cpp.
References Prepare(), PrepareBoundary(), PrepareCP(), PrepareLevelCurves(), PrepareLines(), rsol, and shading.
Referenced by ToggleShading().
void VisualizationSceneSolution::ToggleAttributes (Array< int > & attr_list) [virtual]
Implements VisualizationSceneScalarData.
Definition at line 620 of file vssolution.cpp.
References el_attr_to_show, Prepare(), and PrepareLines().
void VisualizationSceneSolution::ToggleDrawBdr () [inline]
Definition at line 88 of file vssolution.hpp.
References drawbdr.
void VisualizationSceneSolution::ToggleDrawCP () [inline]
Definition at line 112 of file vssolution.hpp.
References draw_cp, and PrepareCP().
void VisualizationSceneSolution::ToggleDrawElems () [inline]
Definition at line 91 of file vssolution.hpp.
References DefaultLevelLines(), drawelems, FindNewBox(), Prepare(), VisualizationSceneScalarData::PrepareAxes(), PrepareBoundary(), PrepareCP(), PrepareLevelCurves(), PrepareLines(), and shading.
void VisualizationSceneSolution::ToggleDrawMesh () [inline]
Definition at line 107 of file vssolution.hpp.
References drawmesh.
void VisualizationSceneSolution::ToggleShading ()
Definition at line 574 of file vssolution.cpp.
References FindNewBox(), Prepare(), VisualizationSceneScalarData::PrepareAxes(), PrepareBoundary(), PrepareCP(), PrepareLevelCurves(), PrepareLines(), rsol, SetShading(), and shading.
Referenced by main().
virtual void VisualizationSceneSolution::UpdateLevelLines () [inline, virtual]
Implements VisualizationSceneScalarData.
Definition at line 67 of file vssolution.hpp.
References PrepareLevelCurves().
Referenced by UpdateValueRange().
void VisualizationSceneSolution::UpdateValueRange () [virtual]
Implements VisualizationSceneScalarData.
Definition at line 1392 of file vssolution.cpp.
References VisualizationSceneScalarData::EventUpdateColors(), VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, NewZRange(), VisualizationSceneScalarData::nl, VisualizationSceneScalarData::PrepareAxes(), VisualizationSceneScalarData::SetLevelLines(), and UpdateLevelLines().
Member Data Documentation
int VisualizationSceneSolution::attr_to_show
Definition at line 51 of file vssolution.hpp.
Referenced by Init().
int VisualizationSceneSolution::bdrlist [protected]
Definition at line 24 of file vssolution.hpp.
Referenced by Draw(), Init(), PrepareBoundary(), and ~VisualizationSceneSolution().
int VisualizationSceneSolution::cp_list [protected]
Definition at line 24 of file vssolution.hpp.
Referenced by VisualizationSceneVector::Draw(), Draw(), Init(), PrepareCP(), and ~VisualizationSceneSolution().
int VisualizationSceneSolution::displlist [protected]
Definition at line 23 of file vssolution.hpp.
Referenced by VisualizationSceneVector::Draw(), Draw(), Init(), Prepare(), PrepareFlat(), PrepareFlat2(), and ~VisualizationSceneSolution().
int VisualizationSceneSolution::draw_cp [protected]
Definition at line 24 of file vssolution.hpp.
Referenced by VisualizationSceneVector::Draw(), Draw(), Init(), PrepareCP(), and ToggleDrawCP().
int VisualizationSceneSolution::drawbdr [protected]
Definition at line 24 of file vssolution.hpp.
Referenced by Draw(), Init(), and ToggleDrawBdr().
int VisualizationSceneSolution::drawelems [protected]
Definition at line 22 of file vssolution.hpp.
Referenced by VisualizationSceneVector::Draw(), Draw(), GetRefinedDetJ(), VisualizationSceneVector::GetRefinedValues(), GetRefinedValues(), GetRefinedValuesAndNormals(), Init(), and ToggleDrawElems().
int VisualizationSceneSolution::drawmesh [protected]
Definition at line 22 of file vssolution.hpp.
Referenced by VisualizationSceneVector::Draw(), Draw(), Init(), and ToggleDrawMesh().
int VisualizationSceneSolution::EdgeRefineFactor
Definition at line 49 of file vssolution.hpp.
Referenced by FindNewBox(), Init(), PrepareBoundary(), PrepareCP(), VisualizationSceneVector::PrepareDisplacedMesh(), PrepareFlat2(), PrepareLevelCurves2(), PrepareLines2(), PrepareLines3(), and SetRefineFactors().
Array<int> VisualizationSceneSolution::el_attr_to_show
Definition at line 52 of file vssolution.hpp.
Referenced by Init(), Prepare(), PrepareFlat(), PrepareFlat2(), PrepareLines(), PrepareLines2(), PrepareLines3(), and ToggleAttributes().
int VisualizationSceneSolution::lcurvelist [protected]
Definition at line 23 of file vssolution.hpp.
Referenced by VisualizationSceneVector::Draw(), Draw(), Init(), PrepareLevelCurves(), PrepareLevelCurves2(), and ~VisualizationSceneSolution().
int VisualizationSceneSolution::linelist [protected]
Definition at line 23 of file vssolution.hpp.
Referenced by VisualizationSceneVector::Draw(), Draw(), Init(), PrepareLines(), PrepareLines2(), PrepareLines3(), and ~VisualizationSceneSolution().
GridFunction* VisualizationSceneSolution::rsol [protected]
Definition at line 20 of file vssolution.hpp.
Referenced by GetRefinedValues(), GetRefinedValuesAndNormals(), Init(), NewMeshAndSolution(), SetGridFunction(), SetShading(), and ToggleShading().
int VisualizationSceneSolution::shading
Definition at line 49 of file vssolution.hpp.
Referenced by FindNewBox(), Init(), KeyuPressed(), Prepare(), PrepareBoundary(), PrepareCP(), VisualizationSceneVector::PrepareDisplacedMesh(), PrepareLevelCurves(), PrepareLines(), VisualizationSceneVector::PrepareVectorField(), SetRefineFactors(), SetShading(), ToggleDrawElems(), and ToggleShading().
int VisualizationSceneSolution::TimesToRefine
Definition at line 49 of file vssolution.hpp.
Referenced by FindNewBox(), Init(), PrepareBoundary(), PrepareCP(), VisualizationSceneVector::PrepareDisplacedMesh(), PrepareFlat2(), PrepareLevelCurves2(), PrepareLines2(), PrepareLines3(), and SetRefineFactors().
The documentation for this class was generated from the following files:
vssolution.hpp
vssolution.cpp