GLVis: VisualizationSceneSolution3d Class Reference
VisualizationSceneSolution3d Class Reference
#include <vssolution3d.hpp>
Public Member Functions
VisualizationSceneSolution3d ()
VisualizationSceneSolution3d (Mesh &m, Vector &s)
void SetGridFunction (GridFunction *gf)
void NewMeshAndSolution (Mesh *new_m, Vector *new_sol, GridFunction *new_u=NULL, int rescale=0)
virtual ~VisualizationSceneSolution3d ()
virtual void FindNewBox ()
virtual void PrepareFlat ()
virtual void PrepareLines ()
virtual void Prepare ()
virtual void Draw ()
void ToggleDrawElems ()
void ToggleDrawMesh ()
void ToggleShading ()
int GetShading ()
virtual void SetShading (int)
virtual void SetRefineFactors (int, int)
virtual void ToggleAttributes (Array< int > &attr_list)
void FindNodePos ()
void CuttingPlaneFunc (int type)
void CPPrepare ()
void CPMoved ()
void PrepareFlat2 ()
void PrepareLines2 ()
virtual void PrepareCuttingPlane ()
void PrepareCuttingPlane2 ()
void PrepareCuttingPlaneLines ()
void PrepareCuttingPlaneLines2 ()
void PrepareLevelSurf ()
void ToggleCuttingPlane ()
void ToggleCPDrawElems ()
void ToggleCPDrawMesh ()
void MoveLevelSurf (int)
void NumberOfLevelSurf (int)
virtual void EventUpdateColors ()
virtual void UpdateLevelLines ()
virtual void UpdateValueRange ()
Public Attributes
int TimesToRefine
double FaceShiftScale
Array< int > bdr_attr_to_show
Protected Member Functions
void Init ()
void GetFaceNormals (const int FaceNo, const int side, const IntegrationRule &ir, DenseMatrix &normals)
void DrawRefinedSurf (int n, double *points, int elem, int func, int part=-1)
void DrawRefinedSurf (int n, DenseMatrix &pointmat, Vector &values, Array< int > &RefGeoms)
void DrawRefinedSurfLevelLines (int n, DenseMatrix &pointmat, Vector &values, Array< int > &RefGeoms)
void DrawRefinedSurfEdges (int n, DenseMatrix &pointmat, Vector &values, Array< int > &RefEdges, int part=-1)
void LiftRefinedSurf (int n, DenseMatrix &pointmat, Vector &values, int *RG)
Protected Attributes
int drawmesh
int drawelems
int shading
int displlist
int linelist
int cplane
int cplanelist
int cplanelineslist
int lsurflist
int cp_drawmesh
int cp_drawelems
int drawlsurf
double * node_pos
int nlevels
Array< double > levels
GridFunction * GridF
Detailed Description
Definition at line 15 of file vssolution3d.hpp.
Constructor & Destructor Documentation
VisualizationSceneSolution3d::VisualizationSceneSolution3d ()
Definition at line 489 of file vssolution3d.cpp.
VisualizationSceneSolution3d::VisualizationSceneSolution3d (Mesh & m, Vector & s)
Definition at line 492 of file vssolution3d.cpp.
References GridF, Init(), VisualizationSceneScalarData::mesh, and VisualizationSceneScalarData::sol.
VisualizationSceneSolution3d::~VisualizationSceneSolution3d () [virtual]
Definition at line 623 of file vssolution3d.cpp.
References cplanelineslist, cplanelist, displlist, linelist, lsurflist, and node_pos.
Member Function Documentation
void VisualizationSceneSolution3d::CPMoved ()
Definition at line 112 of file vssolution3d.cpp.
References cplane, CPPrepare(), Prepare(), and PrepareLines().
void VisualizationSceneSolution3d::CPPrepare ()
Definition at line 106 of file vssolution3d.cpp.
References PrepareCuttingPlane(), and PrepareCuttingPlaneLines().
Referenced by CPMoved(), Init(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), and ToggleCuttingPlane().
void VisualizationSceneSolution3d::CuttingPlaneFunc (int type)
Definition at line 1517 of file vssolution3d.cpp.
References Compute3DUnitNormal(), VisualizationSceneScalarData::DrawPolygonLevelLines(), DrawRefinedSurf(), VisualizationSceneScalarData::level, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), node_pos, shading, and VisualizationSceneScalarData::sol.
Referenced by PrepareCuttingPlane(), and PrepareCuttingPlaneLines().
void VisualizationSceneSolution3d::Draw () [virtual]
Reimplemented from VisualizationScene.
Reimplemented in VisualizationSceneVector3d.
Definition at line 2071 of file vssolution3d.cpp.
References VisualizationSceneScalarData::axeslist, VisualizationSceneScalarData::colorbar, cp_drawelems, cp_drawmesh, cplane, cplanelineslist, cplanelist, VisualizationSceneScalarData::CuttingPlane, displlist, VisualizationSceneScalarData::drawaxes, VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawCoordinateCross(), drawelems, drawlsurf, drawmesh, VisualizationSceneScalarData::DrawRuler(), Plane::Equation(), GetUseTexture(), VisualizationSceneScalarData::level, levels, VisualizationSceneScalarData::light, linelist, lsurflist, MatAlpha, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, Remove_Transparency(), VisualizationScene::rotmat, Set_Background(), Set_Black_Material(), Set_Transparency(), VisualizationScene::translmat, VisualizationScene::x, VisualizationScene::xscale, VisualizationScene::y, VisualizationScene::yscale, VisualizationScene::z, and VisualizationScene::zscale.
void VisualizationSceneSolution3d::DrawRefinedSurf (int n, DenseMatrix & pointmat, Vector & values, Array< int > & RefGeoms) [protected]
Definition at line 988 of file vssolution3d.cpp.
References Compute3DUnitNormal(), VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, and MySetColor().
void VisualizationSceneSolution3d::DrawRefinedSurf (int n, double * points, int elem, int func, int part = -1) [protected]
Definition at line 878 of file vssolution3d.cpp.
References DrawRefinedSurfEdges(), DrawRefinedSurfLevelLines(), GridF, LiftRefinedSurf(), and TimesToRefine.
Referenced by CuttingPlaneFunc().
void VisualizationSceneSolution3d::DrawRefinedSurfEdges (int n, DenseMatrix & pointmat, Vector & values, Array< int > & RefEdges, int part = -1) [protected]
Definition at line 1023 of file vssolution3d.cpp.
Referenced by DrawRefinedSurf(), and PrepareCuttingPlaneLines2().
void VisualizationSceneSolution3d::DrawRefinedSurfLevelLines (int n, DenseMatrix & pointmat, Vector & values, Array< int > & RefGeoms) [protected]
Definition at line 1049 of file vssolution3d.cpp.
References VisualizationSceneScalarData::DrawPolygonLevelLines(), and VisualizationSceneScalarData::level.
Referenced by DrawRefinedSurf(), and PrepareCuttingPlaneLines2().
virtual void VisualizationSceneSolution3d::EventUpdateColors () [inline, virtual]
Reimplemented from VisualizationSceneScalarData.
Reimplemented in VisualizationSceneVector3d.
Definition at line 99 of file vssolution3d.hpp.
References drawmesh, FaceShiftScale, Prepare(), PrepareCuttingPlane(), PrepareLevelSurf(), PrepareLines(), and shading.
Referenced by UpdateValueRange().
void VisualizationSceneSolution3d::FindNewBox () [virtual]
Implements VisualizationSceneScalarData.
Definition at line 733 of file vssolution3d.cpp.
References VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::SetNewScalingFromBox(), VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by NewMeshAndSolution().
void VisualizationSceneSolution3d::FindNodePos ()
Definition at line 759 of file vssolution3d.cpp.
References VisualizationSceneScalarData::CuttingPlane, VisualizationSceneScalarData::mesh, and node_pos.
Referenced by Init(), and NewMeshAndSolution().
void VisualizationSceneSolution3d::GetFaceNormals (const int FaceNo, const int side, const IntegrationRule & ir, DenseMatrix & normals) [protected]
Definition at line 835 of file vssolution3d.cpp.
References VisualizationSceneScalarData::mesh.
Referenced by PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), and PrepareLines2().
int VisualizationSceneSolution3d::GetShading () [inline]
Definition at line 77 of file vssolution3d.hpp.
References shading.
void VisualizationSceneSolution3d::Init () [protected]
Reimplemented from VisualizationSceneScalarData.
Reimplemented in VisualizationSceneVector3d.
Definition at line 506 of file vssolution3d.cpp.
References bdr_attr_to_show, VisualizationSceneScalarData::bdrc, cp_drawelems, cp_drawmesh, cplane, cplanelineslist, cplanelist, CPPrepare(), VisualizationSceneScalarData::CuttingPlane, displlist, drawelems, drawlsurf, drawmesh, FaceShiftScale, FindNodePos(), GridF, KeyIPressed(), KeyUPressed(), KeyuPressed(), KeyVPressed(), KeyvPressed(), linelist, lsurflist, VisualizationSceneScalarData::matc, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, nlevels, node_pos, Prepare(), PrepareLevelSurf(), PrepareLines(), VisualizationSceneScalarData::scaling, Set_Palette(), VisualizationSceneScalarData::SetLevelLines(), VisualizationSceneScalarData::SetNewScalingFromBox(), SetUseTexture(), shading, VisualizationSceneScalarData::shrink, VisualizationSceneScalarData::shrinkmat, VisualizationSceneScalarData::sol, TimesToRefine, ToggleMagicKey(), and VisualizationScene::x.
Referenced by VisualizationSceneSolution3d().
void VisualizationSceneSolution3d::LiftRefinedSurf (int n, DenseMatrix & pointmat, Vector & values, int * RG) [protected]
Definition at line 939 of file vssolution3d.cpp.
References Compute3DUnitNormal(), VisualizationSceneScalarData::CuttingPlane, FaceShiftScale, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by DrawRefinedSurf().
void VisualizationSceneSolution3d::MoveLevelSurf (int move)
Definition at line 809 of file vssolution3d.cpp.
References drawlsurf, and PrepareLevelSurf().
void VisualizationSceneSolution3d::NewMeshAndSolution (Mesh * new_m, Vector * new_sol, GridFunction * new_u = NULL, int rescale = 0)
Definition at line 633 of file vssolution3d.cpp.
References CPPrepare(), FindNewBox(), FindNodePos(), GridF, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, node_pos, Prepare(), VisualizationSceneScalarData::PrepareAxes(), PrepareLevelSurf(), PrepareLines(), and VisualizationSceneScalarData::sol.
Referenced by ExecuteScriptCommand().
void VisualizationSceneSolution3d::NumberOfLevelSurf (int c)
Definition at line 819 of file vssolution3d.cpp.
References nlevels, and PrepareLevelSurf().
void VisualizationSceneSolution3d::Prepare () [virtual]
Reimplemented from VisualizationScene.
Reimplemented in VisualizationSceneVector3d.
Definition at line 1226 of file vssolution3d.cpp.
References bdr_attr_to_show, Compute3DUnitNormal(), cplane, displlist, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), node_pos, PrepareFlat(), PrepareFlat2(), Set_Material(), shading, and VisualizationSceneScalarData::sol.
Referenced by CPMoved(), EventUpdateColors(), Init(), main(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), ToggleAttributes(), and ToggleCuttingPlane().
void VisualizationSceneSolution3d::PrepareCuttingPlane () [virtual]
Reimplemented in VisualizationSceneVector3d.
Definition at line 1721 of file vssolution3d.cpp.
References cp_drawelems, cplane, cplanelist, CuttingPlaneFunc(), PrepareCuttingPlane2(), and Set_Material().
Referenced by CPPrepare(), EventUpdateColors(), and ToggleCPDrawElems().
void VisualizationSceneSolution3d::PrepareCuttingPlane2 ()
Definition at line 1741 of file vssolution3d.cpp.
References cplanelist, DrawPatch(), DrawQuad(), DrawTriangle(), GetFaceNormals(), GridF, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, node_pos, Set_Material(), shading, and TimesToRefine.
Referenced by VisualizationSceneVector3d::PrepareCuttingPlane(), and PrepareCuttingPlane().
void VisualizationSceneSolution3d::PrepareCuttingPlaneLines ()
Definition at line 1816 of file vssolution3d.cpp.
References cp_drawmesh, cplane, cplanelineslist, CuttingPlaneFunc(), and PrepareCuttingPlaneLines2().
Referenced by CPPrepare(), ToggleCPDrawMesh(), and UpdateLevelLines().
void VisualizationSceneSolution3d::PrepareCuttingPlaneLines2 ()
Definition at line 1843 of file vssolution3d.cpp.
References cp_drawmesh, cplanelineslist, VisualizationSceneScalarData::DrawPolygonLevelLines(), DrawRefinedSurfEdges(), DrawRefinedSurfLevelLines(), GridF, VisualizationSceneScalarData::level, VisualizationSceneScalarData::mesh, node_pos, shading, and TimesToRefine.
Referenced by PrepareCuttingPlaneLines().
void VisualizationSceneSolution3d::PrepareFlat () [virtual]
Reimplemented in VisualizationSceneVector3d.
Definition at line 1070 of file vssolution3d.cpp.
References bdr_attr_to_show, cplane, displlist, DrawQuad(), DrawTriangle(), VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, node_pos, and Set_Material().
Referenced by Prepare().
void VisualizationSceneSolution3d::PrepareFlat2 ()
Reimplemented in VisualizationSceneVector3d.
Definition at line 1117 of file vssolution3d.cpp.
References bdr_attr_to_show, cplane, displlist, DrawPatch(), FaceShiftScale, GetFaceNormals(), GridF, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, node_pos, Normalize(), Set_Material(), VisualizationSceneScalarData::ShrinkPoints(), TimesToRefine, VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by Prepare().
void VisualizationSceneSolution3d::PrepareLevelSurf ()
Definition at line 1931 of file vssolution3d.cpp.
References Compute3DUnitNormal(), drawlsurf, levels, lsurflist, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, MySetColor(), nlevels, and Set_Material().
Referenced by EventUpdateColors(), Init(), MoveLevelSurf(), NewMeshAndSolution(), and NumberOfLevelSurf().
void VisualizationSceneSolution3d::PrepareLines () [virtual]
Implements VisualizationSceneScalarData.
Reimplemented in VisualizationSceneVector3d.
Definition at line 1342 of file vssolution3d.cpp.
References bdr_attr_to_show, cplane, drawmesh, VisualizationSceneScalarData::DrawPolygonLevelLines(), VisualizationSceneScalarData::level, linelist, VisualizationSceneScalarData::mesh, node_pos, PrepareLines2(), and shading.
Referenced by CPMoved(), EventUpdateColors(), Init(), NewMeshAndSolution(), SetRefineFactors(), SetShading(), ToggleAttributes(), ToggleCuttingPlane(), ToggleDrawMesh(), and UpdateLevelLines().
void VisualizationSceneSolution3d::PrepareLines2 ()
Reimplemented in VisualizationSceneVector3d.
Definition at line 1412 of file vssolution3d.cpp.
References bdr_attr_to_show, cplane, drawmesh, VisualizationSceneScalarData::DrawPolygonLevelLines(), FaceShiftScale, GetFaceNormals(), GridF, InnerProd(), VisualizationSceneScalarData::level, linelist, VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::mesh, VisualizationSceneScalarData::minv, node_pos, VisualizationSceneScalarData::ShrinkPoints(), TimesToRefine, VisualizationScene::x, VisualizationScene::y, and VisualizationScene::z.
Referenced by PrepareLines().
void VisualizationSceneSolution3d::SetGridFunction (GridFunction * gf) [inline]
Definition at line 57 of file vssolution3d.hpp.
References GridF.
Referenced by main(), and PlayScript().
void VisualizationSceneSolution3d::SetRefineFactors (int f, int ignored) [virtual]
Implements VisualizationSceneScalarData.
Definition at line 692 of file vssolution3d.cpp.
References CPPrepare(), Prepare(), PrepareLines(), shading, and TimesToRefine.
void VisualizationSceneSolution3d::SetShading (int s) [virtual]
Implements VisualizationSceneScalarData.
Definition at line 663 of file vssolution3d.cpp.
References CPPrepare(), GridF, Prepare(), PrepareLines(), and shading.
Referenced by ToggleShading().
void VisualizationSceneSolution3d::ToggleAttributes (Array< int > & attr_list) [virtual]
Implements VisualizationSceneScalarData.
Definition at line 707 of file vssolution3d.cpp.
References bdr_attr_to_show, Prepare(), and PrepareLines().
void VisualizationSceneSolution3d::ToggleCPDrawElems ()
Definition at line 792 of file vssolution3d.cpp.
References cp_drawelems, and PrepareCuttingPlane().
void VisualizationSceneSolution3d::ToggleCPDrawMesh ()
Definition at line 799 of file vssolution3d.cpp.
References cp_drawmesh, cplane, and PrepareCuttingPlaneLines().
void VisualizationSceneSolution3d::ToggleCuttingPlane ()
Definition at line 774 of file vssolution3d.cpp.
References cp_drawmesh, cplane, CPPrepare(), Prepare(), and PrepareLines().
void VisualizationSceneSolution3d::ToggleDrawElems () [inline]
Definition at line 71 of file vssolution3d.hpp.
References drawelems.
void VisualizationSceneSolution3d::ToggleDrawMesh ()
Definition at line 767 of file vssolution3d.cpp.
References drawmesh, and PrepareLines().
Referenced by main().
void VisualizationSceneSolution3d::ToggleShading ()
Definition at line 684 of file vssolution3d.cpp.
References GridF, SetShading(), and shading.
Referenced by main().
virtual void VisualizationSceneSolution3d::UpdateLevelLines () [inline, virtual]
Implements VisualizationSceneScalarData.
Definition at line 105 of file vssolution3d.hpp.
References PrepareCuttingPlaneLines(), and PrepareLines().
Referenced by UpdateValueRange().
virtual void VisualizationSceneSolution3d::UpdateValueRange () [inline, virtual]
Implements VisualizationSceneScalarData.
Definition at line 107 of file vssolution3d.hpp.
References EventUpdateColors(), VisualizationSceneScalarData::maxv, VisualizationSceneScalarData::minv, VisualizationSceneScalarData::nl, VisualizationSceneScalarData::SetLevelLines(), and UpdateLevelLines().
Referenced by VisualizationSceneVector3d::ToggleScalarFunction().
Member Data Documentation
Array<int> VisualizationSceneSolution3d::bdr_attr_to_show
Definition at line 52 of file vssolution3d.hpp.
Referenced by Init(), VisualizationSceneVector3d::Prepare(), Prepare(), VisualizationSceneVector3d::PrepareFlat(), PrepareFlat(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), VisualizationSceneVector3d::PrepareLines(), PrepareLines(), VisualizationSceneVector3d::PrepareLines2(), PrepareLines2(), and ToggleAttributes().
int VisualizationSceneSolution3d::cp_drawelems [protected]
Definition at line 22 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), Init(), VisualizationSceneVector3d::PrepareCuttingPlane(), PrepareCuttingPlane(), and ToggleCPDrawElems().
int VisualizationSceneSolution3d::cp_drawmesh [protected]
Definition at line 22 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), Init(), PrepareCuttingPlaneLines(), PrepareCuttingPlaneLines2(), ToggleCPDrawMesh(), and ToggleCuttingPlane().
int VisualizationSceneSolution3d::cplane [protected]
Definition at line 21 of file vssolution3d.hpp.
Referenced by CPMoved(), VisualizationSceneVector3d::Draw(), Draw(), Init(), Prepare(), VisualizationSceneVector3d::PrepareCuttingPlane(), PrepareCuttingPlane(), PrepareCuttingPlaneLines(), PrepareFlat(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), PrepareLines(), VisualizationSceneVector3d::PrepareLines2(), PrepareLines2(), ToggleCPDrawMesh(), and ToggleCuttingPlane().
int VisualizationSceneSolution3d::cplanelineslist [protected]
Definition at line 21 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), Init(), PrepareCuttingPlaneLines(), PrepareCuttingPlaneLines2(), and ~VisualizationSceneSolution3d().
int VisualizationSceneSolution3d::cplanelist [protected]
Definition at line 21 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), Init(), VisualizationSceneVector3d::PrepareCuttingPlane(), PrepareCuttingPlane(), PrepareCuttingPlane2(), and ~VisualizationSceneSolution3d().
int VisualizationSceneSolution3d::displlist [protected]
Definition at line 20 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), Init(), VisualizationSceneVector3d::Prepare(), Prepare(), VisualizationSceneVector3d::PrepareFlat(), PrepareFlat(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), and ~VisualizationSceneSolution3d().
int VisualizationSceneSolution3d::drawelems [protected]
Definition at line 19 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), Init(), and ToggleDrawElems().
int VisualizationSceneSolution3d::drawlsurf [protected]
Definition at line 22 of file vssolution3d.hpp.
Referenced by Draw(), Init(), MoveLevelSurf(), and PrepareLevelSurf().
int VisualizationSceneSolution3d::drawmesh [protected]
Definition at line 19 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), EventUpdateColors(), Init(), VisualizationSceneVector3d::PrepareLines(), PrepareLines(), VisualizationSceneVector3d::PrepareLines2(), PrepareLines2(), VisualizationSceneVector3d::PrepareVectorField(), and ToggleDrawMesh().
double VisualizationSceneSolution3d::FaceShiftScale
Definition at line 50 of file vssolution3d.hpp.
Referenced by EventUpdateColors(), Init(), LiftRefinedSurf(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), VisualizationSceneVector3d::PrepareLines2(), and PrepareLines2().
GridFunction* VisualizationSceneSolution3d::GridF [protected]
Definition at line 29 of file vssolution3d.hpp.
Referenced by DrawRefinedSurf(), Init(), NewMeshAndSolution(), PrepareCuttingPlane2(), PrepareCuttingPlaneLines2(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), VisualizationSceneVector3d::PrepareLines2(), PrepareLines2(), SetGridFunction(), VisualizationSceneVector3d::SetScalarFunction(), SetShading(), ToggleShading(), VisualizationSceneSolution3d(), VisualizationSceneVector3d::VisualizationSceneVector3d(), and VisualizationSceneVector3d::~VisualizationSceneVector3d().
Array<double> VisualizationSceneSolution3d::levels [protected]
Definition at line 27 of file vssolution3d.hpp.
Referenced by Draw(), and PrepareLevelSurf().
int VisualizationSceneSolution3d::linelist [protected]
Definition at line 20 of file vssolution3d.hpp.
Referenced by VisualizationSceneVector3d::Draw(), Draw(), Init(), VisualizationSceneVector3d::PrepareLines(), PrepareLines(), VisualizationSceneVector3d::PrepareLines2(), PrepareLines2(), and ~VisualizationSceneSolution3d().
int VisualizationSceneSolution3d::lsurflist [protected]
Definition at line 21 of file vssolution3d.hpp.
Referenced by Draw(), Init(), PrepareLevelSurf(), and ~VisualizationSceneSolution3d().
int VisualizationSceneSolution3d::nlevels [protected]
Definition at line 26 of file vssolution3d.hpp.
Referenced by Init(), NumberOfLevelSurf(), and PrepareLevelSurf().
double* VisualizationSceneSolution3d::node_pos [protected]
Definition at line 24 of file vssolution3d.hpp.
Referenced by CuttingPlaneFunc(), FindNodePos(), Init(), NewMeshAndSolution(), Prepare(), VisualizationSceneVector3d::PrepareCuttingPlane(), PrepareCuttingPlane2(), PrepareCuttingPlaneLines2(), PrepareFlat(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), PrepareLines(), VisualizationSceneVector3d::PrepareLines2(), PrepareLines2(), and ~VisualizationSceneSolution3d().
int VisualizationSceneSolution3d::shading [protected]
Definition at line 19 of file vssolution3d.hpp.
Referenced by CuttingPlaneFunc(), EventUpdateColors(), GetShading(), Init(), VisualizationSceneVector3d::Prepare(), Prepare(), PrepareCuttingPlane2(), PrepareCuttingPlaneLines2(), VisualizationSceneVector3d::PrepareLines(), PrepareLines(), SetRefineFactors(), SetShading(), and ToggleShading().
int VisualizationSceneSolution3d::TimesToRefine
Definition at line 49 of file vssolution3d.hpp.
Referenced by DrawRefinedSurf(), Init(), PrepareCuttingPlane2(), PrepareCuttingPlaneLines2(), VisualizationSceneVector3d::PrepareFlat2(), PrepareFlat2(), VisualizationSceneVector3d::PrepareLines2(), PrepareLines2(), and SetRefineFactors().
The documentation for this class was generated from the following files:
vssolution3d.hpp
vssolution3d.cpp