GLVis: communication_thread Class Reference
communication_thread Class Reference
#include <threads.hpp>
Public Member Functions
communication_thread (Array< istream * > &_is)
~communication_thread ()
Static Private Member Functions
static void cancel_off ()
static void cancel_on ()
static void * execute (void *)
Private Attributes
Array< istream * > & is
Mesh * new_m
GridFunction * new_g
string ident
pthread_t tid
Detailed Description
Definition at line 73 of file threads.hpp.
Constructor & Destructor Documentation
communication_thread::communication_thread (Array< istream * > & _is)
Definition at line 211 of file threads.cpp.
References execute(), is, new_g, new_m, and tid.
communication_thread::~communication_thread ()
Definition at line 221 of file threads.cpp.
References is, new_g, new_m, and tid.
Member Function Documentation
static void communication_thread::cancel_off () [inline, static, private]
Definition at line 87 of file threads.hpp.
Referenced by execute().
static void communication_thread::cancel_on () [inline, static, private]
Definition at line 92 of file threads.hpp.
Referenced by execute().
void * communication_thread::execute (void * p) [static, private]
Definition at line 233 of file threads.cpp.
References cancel_off(), cancel_on(), ident, is, keep_attr, GLVisCommand::KeepAttrib(), new_g, new_m, GLVisCommand::NewMeshAndSolution(), and np.
Referenced by communication_thread().
Member Data Documentation
string communication_thread::ident [private]
Definition at line 82 of file threads.hpp.
Referenced by execute().
Array<istream *>& communication_thread::is [private]
Definition at line 77 of file threads.hpp.
Referenced by communication_thread(), execute(), and ~communication_thread().
GridFunction* communication_thread::new_g [private]
Definition at line 81 of file threads.hpp.
Referenced by communication_thread(), execute(), and ~communication_thread().
Mesh* communication_thread::new_m [private]
Definition at line 80 of file threads.hpp.
Referenced by communication_thread(), execute(), and ~communication_thread().
pthread_t communication_thread::tid [private]
Definition at line 85 of file threads.hpp.
Referenced by communication_thread(), and ~communication_thread().
The documentation for this class was generated from the following files:
threads.hpp
threads.cpp