GLVis: glvis.cpp File Reference
glvis.cpp File Reference
#include <limits>
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include "mfem.hpp"
#include "lib/visual.hpp"
#include <X11/keysym.h>
#include <unistd.h>
Functions
void Set_Palette (int)
void ReadSerial ()
void ReadParallel ()
int InitVis (int t)
void VisStream (istream *iss, char *data_type)
int ScriptReadSolution (istream &scr, Mesh **mp, GridFunction **sp)
int ScriptReadDisplMesh (istream &scr, Mesh **mp, GridFunction **sp)
void ExecuteScriptCommand ()
void ScriptControl ()
void ScriptIdleFunc ()
void PlayScript (istream &scr)
int main (int argc, char *argv[])
Variables
char ** environ
VisualizationSceneScalarData * vs = NULL
int portnum = 19916
int input = 1
int np = 4
char mesh_file [128]
char sol_file [128]
char keys [1000]
Mesh * mesh = NULL
Vector sol
Vector solu
Vector solv
Vector solw
Vector * data [3] = {NULL, NULL, NULL}
int is_gf = 0
int gf_component = -1
GridFunction * grid_f = NULL
int mac = 0
int viscount = 0
int save_coloring = 0
int window_x = 0
int window_y = 0
int window_w = 400
int window_h = 350
const char * window_titles [2]
istream * script = NULL
int scr_sol_autoscale = 0
int scr_running = 0
int scr_level = 0
Vector * init_nodes = NULL
double scr_min_val
double scr_max_val
Function Documentation
void ExecuteScriptCommand ()
Definition at line 317 of file glvis.cpp.
References VisualizationScene::Draw(), VisualizationSceneScalarData::EventUpdateColors(), VisualizationSceneScalarData::GetMaxV(), VisualizationSceneScalarData::GetMinV(), grid_f, keys, VisualizationSceneScalarData::light, mesh, MoveResizeWindow(), MyExpose(), VisualizationSceneSolution3d::NewMeshAndSolution(), VisualizationSceneVector::NewMeshAndSolution(), VisualizationSceneSolution::NewMeshAndSolution(), VisualizationScene::OrthogonalProjection, scr_level, scr_max_val, scr_min_val, scr_sol_autoscale, Screenshot(), script, ScriptReadDisplMesh(), ScriptReadSolution(), SendKeySequence(), Set_Palette(), VisualizationSceneScalarData::SetRefineFactors(), VisualizationSceneScalarData::SetShading(), VisualizationSceneScalarData::SetValueRange(), VisualizationScene::SetView(), sol, VisualizationSceneScalarData::ToggleAttributes(), VisualizationScene::ViewCenterX, VisualizationScene::ViewCenterY, vs, window_h, window_w, window_x, window_y, and VisualizationScene::Zoom().
Referenced by ScriptIdleFunc().
int InitVis (int t)
Definition at line 64 of file glvis.cpp.
References InitVisualization(), window_h, window_titles, window_w, window_x, and window_y.
Referenced by main(), PlayScript(), and VisStream().
int main (int argc, char * argv[])
Definition at line 770 of file glvis.cpp.
References data, environ, gf_component, grid_f, InitVis(), input, is_gf, keys, KillVisualization(), VisualizationSceneScalarData::light, mac, mesh, mesh_file, np, VisualizationScene::OrthogonalProjection, PlayScript(), portnum, VisualizationSceneSolution3d::Prepare(), ReadParallel(), ReadSerial(), save_coloring, Set_Material_And_Light(), Set_Palette(), VisualizationSceneSolution3d::SetGridFunction(), VisualizationSceneSolution::SetGridFunction(), VisualizationSceneScalarData::SetRefineFactors(), VisualizationSceneScalarData::SetValueRange(), SetVisualizationScene(), sol, sol_file, solu, solv, solw, VisualizationSceneScalarData::ToggleDrawAxes(), VisualizationSceneSolution3d::ToggleDrawMesh(), VisualizationSceneSolution3d::ToggleShading(), VisualizationSceneSolution::ToggleShading(), viscount, VisStream(), and VisualizationScene::Zoom().
void PlayScript (istream & scr)
Definition at line 664 of file glvis.cpp.
References grid_f, init_nodes, InitVis(), KillVisualization(), mesh, scr_level, scr_max_val, scr_min_val, scr_running, script, ScriptControl(), ScriptReadDisplMesh(), ScriptReadSolution(), VisualizationSceneSolution3d::SetGridFunction(), VisualizationSceneSolution::SetGridFunction(), SetVisualizationScene(), sol, window_h, window_w, window_x, and window_y.
Referenced by main().
void ReadParallel ()
Definition at line 1231 of file glvis.cpp.
References input, mesh, mesh_file, np, sol, sol_file, solu, solv, and solw.
Referenced by main().
void ReadSerial ()
Definition at line 1116 of file glvis.cpp.
References gf_component, grid_f, input, is_gf, mesh, mesh_file, save_coloring, sol, sol_file, solu, solv, and solw.
Referenced by main().
void ScriptControl ()
Definition at line 650 of file glvis.cpp.
References AddIdleFunc(), RemoveIdleFunc(), scr_running, and ScriptIdleFunc().
Referenced by PlayScript(), and ScriptIdleFunc().
void ScriptIdleFunc ()
Definition at line 643 of file glvis.cpp.
References ExecuteScriptCommand(), scr_level, and ScriptControl().
Referenced by ScriptControl().
int ScriptReadDisplMesh (istream & scr, Mesh ** mp, GridFunction ** sp)
Definition at line 260 of file glvis.cpp.
References init_nodes, and mesh.
Referenced by ExecuteScriptCommand(), and PlayScript().
int ScriptReadSolution (istream & scr, Mesh ** mp, GridFunction ** sp)
Definition at line 225 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), and PlayScript().
void Set_Palette (int)
Definition at line 3127 of file palettes.hpp.
Referenced by ExecuteScriptCommand(), VisualizationSceneSolution3d::Init(), main(), Next_RGB_Palette(), and Select_New_RGB_Palette().
void VisStream (istream * iss, char * data_type)
Definition at line 71 of file glvis.cpp.
References data, grid_f, InitVis(), keys, KillVisualization(), mesh, SetVisualizationScene(), sol, solu, solv, and solw.
Referenced by main().
Variable Documentation
Vector * data[3] = {NULL, NULL, NULL}
Definition at line 38 of file glvis.cpp.
Referenced by main(), and VisStream().
char** environ
Referenced by main().
int gf_component = -1
Definition at line 39 of file glvis.cpp.
Referenced by main(), and ReadSerial().
GridFunction* grid_f = NULL
Definition at line 40 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), main(), PlayScript(), ReadSerial(), and VisStream().
Vector* init_nodes = NULL
Definition at line 55 of file glvis.cpp.
Referenced by PlayScript(), and ScriptReadDisplMesh().
int input = 1
Definition at line 35 of file glvis.cpp.
Referenced by main(), ReadParallel(), and ReadSerial().
int is_gf = 0
Definition at line 39 of file glvis.cpp.
Referenced by main(), and ReadSerial().
char keys[1000]
Definition at line 36 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), main(), and VisStream().
int mac = 0
Definition at line 41 of file glvis.cpp.
Referenced by main().
Mesh* mesh = NULL
Definition at line 37 of file glvis.cpp.
Referenced by VisualizationSceneScalarData::ComputeBdrAttrCenter(), VisualizationSceneScalarData::ComputeElemAttrCenter(), ExecuteScriptCommand(), main(), PlayScript(), ReadParallel(), ReadSerial(), ScriptReadDisplMesh(), VisualizationSceneScalarData::ShrinkPoints(), VisStream(), and VisualizationSceneScalarData::VisualizationSceneScalarData().
char mesh_file[128]
Definition at line 36 of file glvis.cpp.
Referenced by main(), ReadParallel(), and ReadSerial().
int np = 4
Definition at line 35 of file glvis.cpp.
Referenced by main(), and ReadParallel().
int portnum = 19916
Definition at line 35 of file glvis.cpp.
Referenced by main().
int save_coloring = 0
Definition at line 43 of file glvis.cpp.
Referenced by main(), and ReadSerial().
int scr_level = 0
Definition at line 54 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), PlayScript(), and ScriptIdleFunc().
double scr_max_val
Definition at line 56 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), and PlayScript().
double scr_min_val
Definition at line 56 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), and PlayScript().
int scr_running = 0
Definition at line 53 of file glvis.cpp.
Referenced by PlayScript(), and ScriptControl().
int scr_sol_autoscale = 0
Definition at line 52 of file glvis.cpp.
Referenced by ExecuteScriptCommand().
istream* script = NULL
Definition at line 51 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), and PlayScript().
Vector sol
Definition at line 38 of file glvis.cpp.
Referenced by ArrowsDrawOrNot(), ExecuteScriptCommand(), main(), PlayScript(), ReadParallel(), ReadSerial(), VisStream(), and VisualizationSceneScalarData::VisualizationSceneScalarData().
char sol_file[128]
Definition at line 36 of file glvis.cpp.
Referenced by main(), ReadParallel(), and ReadSerial().
Vector solu
Definition at line 38 of file glvis.cpp.
Referenced by main(), ReadParallel(), ReadSerial(), and VisStream().
Vector solv
Definition at line 38 of file glvis.cpp.
Referenced by main(), ReadParallel(), ReadSerial(), and VisStream().
Vector solw
Definition at line 38 of file glvis.cpp.
Referenced by main(), ReadParallel(), ReadSerial(), and VisStream().
int viscount = 0
Definition at line 42 of file glvis.cpp.
Referenced by main().
VisualizationSceneScalarData* vs = NULL
Definition at line 33 of file glvis.cpp.
Referenced by ExecuteScriptCommand().
int window_h = 350
Definition at line 48 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), InitVis(), and PlayScript().
const char* window_titles[2]
Initial value:
{ "GLVis [scalar data]",
                                "GLVis [vector data]" }
Definition at line 49 of file glvis.cpp.
Referenced by InitVis().
int window_w = 400
Definition at line 47 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), InitVis(), and PlayScript().
int window_x = 0
Definition at line 45 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), InitVis(), and PlayScript().
int window_y = 0
Definition at line 46 of file glvis.cpp.
Referenced by ExecuteScriptCommand(), InitVis(), and PlayScript().