GLVis: material.hpp File Reference
material.hpp File Reference
Functions
void Set_Material ()
void Set_Light ()
int Next_Material_And_Light ()
void Set_Material_And_Light (int, int)
void Set_Black_Material ()
void Set_Background ()
void Toggle_Background ()
void Set_Transparency ()
void Remove_Transparency ()
void Set_AntiAliasing ()
void Remove_AntiAliasing ()
Function Documentation
int Next_Material_And_Light ()
Definition at line 240 of file material.cpp.
References Current_Material, Num_Materials, Set_Light(), and Set_Material().
Referenced by KeyTPressed().
void Remove_AntiAliasing ()
Definition at line 380 of file material.cpp.
Referenced by KeyAPressed().
void Remove_Transparency ()
Definition at line 324 of file material.cpp.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), and VisualizationSceneSolution::Draw().
void Set_AntiAliasing ()
Definition at line 330 of file material.cpp.
Referenced by KeyAPressed().
void Set_Background ()
Definition at line 299 of file material.cpp.
References Background.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), and VisualizationSceneSolution::Draw().
void Set_Black_Material ()
Definition at line 259 of file material.cpp.
References Background.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), VisualizationSceneSolution::Draw(), VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawRuler(), and VisualizationSceneScalarData::PrepareAxes().
void Set_Light ()
Definition at line 109 of file material.cpp.
References Current_Material.
Referenced by VisualizationSceneScalarData::CenterObject(), VisualizationSceneScalarData::CenterObject2D(), VisualizationSceneScalarData::Init(), KeyRPressed(), Next_Material_And_Light(), and Set_Material_And_Light().
void Set_Material ()
Definition at line 20 of file material.cpp.
References Current_Material.
Referenced by VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawRuler(), Next_Material_And_Light(), VisualizationSceneVector3d::Prepare(), VisualizationSceneSolution3d::Prepare(), VisualizationSceneSolution::Prepare(), VisualizationSceneVector3d::PrepareCuttingPlane(), VisualizationSceneSolution3d::PrepareCuttingPlane(), VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareDisplacedMesh(), VisualizationSceneVector3d::PrepareFlat(), VisualizationSceneSolution3d::PrepareFlat(), VisualizationSceneSolution::PrepareFlat(), VisualizationSceneVector3d::PrepareFlat2(), VisualizationSceneSolution3d::PrepareFlat2(), VisualizationSceneSolution::PrepareFlat2(), VisualizationSceneSolution3d::PrepareLevelSurf(), VisualizationSceneVector3d::PrepareVectorField(), and Set_Material_And_Light().
void Set_Material_And_Light (int , int)
Definition at line 249 of file material.cpp.
References Current_Material, Set_Light(), and Set_Material().
Referenced by main().
void Set_Transparency ()
Definition at line 317 of file material.cpp.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), and VisualizationSceneSolution::Draw().
void Toggle_Background ()
Definition at line 312 of file material.cpp.
References Background.
Referenced by KeyGPressed().