GLVis: material.cpp File Reference
material.cpp File Reference
#include <GL/gl.h>
#include <GL/glu.h>
#include <GL/glx.h>
#include <string>
Functions
void Set_Material ()
void Set_Light ()
int Next_Material_And_Light ()
void Set_Material_And_Light (int m, int l)
void Set_Black_Material ()
void Set_Background ()
void Toggle_Background ()
void Set_Transparency ()
void Remove_Transparency ()
void Set_AntiAliasing ()
void Remove_AntiAliasing ()
Variables
int Num_Materials = 5
int Current_Material = 3
int Background = 1
Function Documentation
int Next_Material_And_Light ()
Definition at line 240 of file material.cpp.
References Current_Material, Num_Materials, Set_Light(), and Set_Material().
Referenced by KeyTPressed().
void Remove_AntiAliasing ()
Definition at line 376 of file material.cpp.
Referenced by KeyAPressed().
void Remove_Transparency ()
Definition at line 324 of file material.cpp.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), and VisualizationSceneSolution::Draw().
void Set_AntiAliasing ()
Definition at line 330 of file material.cpp.
Referenced by KeyAPressed().
void Set_Background ()
Definition at line 299 of file material.cpp.
References Background.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), and VisualizationSceneSolution::Draw().
void Set_Black_Material ()
Definition at line 259 of file material.cpp.
References Background.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), VisualizationSceneSolution::Draw(), VisualizationSceneScalarData::DrawColorBar(), and VisualizationSceneScalarData::DrawRuler().
void Set_Light ()
Definition at line 109 of file material.cpp.
References Current_Material.
Referenced by VisualizationSceneScalarData::CenterObject(), VisualizationSceneScalarData::CenterObject2D(), VisualizationSceneScalarData::Init(), KeyRPressed(), Next_Material_And_Light(), and Set_Material_And_Light().
void Set_Material ()
Definition at line 20 of file material.cpp.
References Current_Material.
Referenced by VisualizationSceneScalarData::DrawColorBar(), VisualizationSceneScalarData::DrawRuler(), Next_Material_And_Light(), VisualizationSceneVector3d::Prepare(), VisualizationSceneSolution3d::Prepare(), VisualizationSceneSolution::Prepare(), VisualizationSceneVector3d::PrepareCuttingPlane(), VisualizationSceneSolution3d::PrepareCuttingPlane(), VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareDisplacedMesh(), VisualizationSceneVector3d::PrepareFlat(), VisualizationSceneSolution3d::PrepareFlat(), VisualizationSceneSolution::PrepareFlat(), VisualizationSceneVector3d::PrepareFlat2(), VisualizationSceneSolution3d::PrepareFlat2(), VisualizationSceneSolution::PrepareFlat2(), VisualizationSceneSolution3d::PrepareLevelSurf(), VisualizationSceneVector3d::PrepareVectorField(), and Set_Material_And_Light().
void Set_Material_And_Light (int m, int l)
Definition at line 249 of file material.cpp.
References Current_Material, Set_Light(), and Set_Material().
Referenced by main().
void Set_Transparency ()
Definition at line 317 of file material.cpp.
Referenced by VisualizationSceneVector3d::Draw(), VisualizationSceneVector::Draw(), VisualizationSceneSolution3d::Draw(), and VisualizationSceneSolution::Draw().
void Toggle_Background ()
Definition at line 312 of file material.cpp.
References Background.
Referenced by KeyGPressed().
Variable Documentation
int Background = 1
Definition at line 257 of file material.cpp.
Referenced by Set_Background(), Set_Black_Material(), and Toggle_Background().
int Current_Material = 3
Definition at line 18 of file material.cpp.
Referenced by Next_Material_And_Light(), Set_Light(), Set_Material(), and Set_Material_And_Light().
int Num_Materials = 5
Definition at line 17 of file material.cpp.
Referenced by Next_Material_And_Light().