GLVis: palettes.hpp File Reference
palettes.hpp File Reference
#include <stdio.h>
#include <iostream>
#include <iomanip>
Functions
double corr (double a, double x)
void Init_Visit_Calewhite_Palette ()
void Init_Palettes ()
void Set_Texture_Image ()
void Set_Palette (int num)
void Next_RGB_Palette ()
int Select_New_RGB_Palette ()
Variables
const int RGB_Palette_1_Size = 5
double RGB_Palette_1 [RGB_Palette_1_Size][3]
const int RGB_Palette_2_Size = 2
double RGB_Palette_2 [RGB_Palette_2_Size][3]
const int RGB_Palette_3_Size = 65
double RGB_Palette_3 [RGB_Palette_3_Size][3]
const int RGB_Palette_4_Size = 2
double RGB_Palette_4 [RGB_Palette_4_Size][3]
const int RGB_Palette_5_Size = 64
double RGB_Palette_5 [RGB_Palette_5_Size][3]
const int RGB_Palette_6_Size = 64
double RGB_Palette_6 [RGB_Palette_6_Size][3]
const int RGB_Palette_7_Size = 64
double RGB_Palette_7 [RGB_Palette_7_Size][3]
const int RGB_Palette_8_Size = 64
double RGB_Palette_8 [RGB_Palette_8_Size][3]
const int RGB_Palette_9_Size = 64
double RGB_Palette_9 [RGB_Palette_9_Size][3]
const int RGB_Palette_10_Size = 64
double RGB_Palette_10 [RGB_Palette_10_Size][3]
const int RGB_Palette_11_Size = 64
double RGB_Palette_11 [RGB_Palette_11_Size][3]
const int RGB_Palette_12_Size = 2
double RGB_Palette_12 [RGB_Palette_12_Size][3]
const int RGB_Palette_13_Size = (4*16+1)
double RGB_Palette_13 [RGB_Palette_13_Size][3]
const int RGB_Palette_14_Size = 256
double RGB_Palette_14 [RGB_Palette_14_Size][3]
const int RGB_Palette_15_Size = 256
double RGB_Palette_15 [RGB_Palette_15_Size][3]
const int RGB_Palette_16_Size = 256
double RGB_Palette_16 [RGB_Palette_16_Size][3]
const int RGB_Palette_17_Size = 255
double RGB_Palette_17 [RGB_Palette_17_Size][3]
const int RGB_Palette_18_Size = 256
double RGB_Palette_18 [RGB_Palette_18_Size][3]
const int RGB_Palette_19_Size = 256
double RGB_Palette_19 [RGB_Palette_19_Size][3]
const int RGB_Palette_20_Size = 256
double RGB_Palette_20 [RGB_Palette_20_Size][3]
const int RGB_Palette_21_Size = 256
double RGB_Palette_21 [RGB_Palette_21_Size][3]
const int RGB_Palette_22_Size = 151
double RGB_Palette_22 [RGB_Palette_22_Size][3]
const int RGB_Palette_23_Size = 6*32+1
double RGB_Palette_23 [RGB_Palette_23_Size][3]
const int RGB_Palette_24_Size = 31
double RGB_Palette_24 [RGB_Palette_24_Size][3]
const int RGB_Palette_25_Size = (4*16+1)
double RGB_Palette_25 [RGB_Palette_25_Size][3]
const int Num_RGB_Palettes = 25
const int RGB_Palettes_Sizes [Num_RGB_Palettes]
double * RGB_Palettes [Num_RGB_Palettes]
const char * RGB_Palettes_Names [Num_RGB_Palettes]
int Default_RGB_Palette = 2
int RGB_Palette_Size = RGB_Palettes_Sizes[Default_RGB_Palette]
double * RGB_Palette = RGB_Palettes[Default_RGB_Palette]
Function Documentation
double corr (double a, double x)
Definition at line 3002 of file palettes.hpp.
Referenced by Init_Palettes(), and Init_Visit_Calewhite_Palette().
void Init_Palettes ()
Definition at line 3037 of file palettes.hpp.
References corr(), Init_Visit_Calewhite_Palette(), RGB_Palette_13, RGB_Palette_13_Size, RGB_Palette_23, and RGB_Palette_23_Size.
Referenced by InitVisualization().
void Init_Visit_Calewhite_Palette ()
Definition at line 3008 of file palettes.hpp.
References corr(), RGB_Palette_25, and RGB_Palette_25_Size.
Referenced by Init_Palettes().
void Next_RGB_Palette ()
Definition at line 3136 of file palettes.hpp.
References Default_RGB_Palette, Num_RGB_Palettes, and Set_Palette().
Referenced by KeyPPressed().
int Select_New_RGB_Palette ()
Definition at line 3141 of file palettes.hpp.
References Default_RGB_Palette, Num_RGB_Palettes, RGB_Palettes_Names, and Set_Palette().
Referenced by KeyF6Pressed().
void Set_Palette (int num)
Definition at line 3127 of file palettes.hpp.
References Default_RGB_Palette, RGB_Palette, RGB_Palette_Size, RGB_Palettes, RGB_Palettes_Sizes, and Set_Texture_Image().
Referenced by ExecuteScriptCommand(), VisualizationSceneSolution3d::Init(), main(), Next_RGB_Palette(), and Select_New_RGB_Palette().
void Set_Texture_Image ()
Definition at line 1272 of file aux_vis.cpp.
References Make_Texture_From_Palette(), and Make_Texture_From_Palette_2().
Referenced by InitVisualization(), Set_Palette(), and SetUseTexture().
Variable Documentation
int Default_RGB_Palette = 2
Definition at line 2998 of file palettes.hpp.
Referenced by Next_RGB_Palette(), Select_New_RGB_Palette(), and Set_Palette().
const int Num_RGB_Palettes = 25
Definition at line 2964 of file palettes.hpp.
Referenced by Next_RGB_Palette(), and Select_New_RGB_Palette().
double* RGB_Palette = RGB_Palettes[Default_RGB_Palette]
Definition at line 3000 of file palettes.hpp.
Referenced by Make_Texture_From_Palette(), Make_Texture_From_Palette_2(), MySetColor(), and Set_Palette().
double RGB_Palette_1[RGB_Palette_1_Size][3]
Initial value:
{
   { 0, 0, 1 },
   { 0, 1, 1 },
   { 0, 1, 0 },
   { 1, 1, 0 },
   { 1, 0, 0 }
}
Definition at line 22 of file palettes.hpp.
double RGB_Palette_10[RGB_Palette_10_Size][3]
Definition at line 489 of file palettes.hpp.
const int RGB_Palette_10_Size = 64
Definition at line 488 of file palettes.hpp.
double RGB_Palette_11[RGB_Palette_11_Size][3]
Definition at line 558 of file palettes.hpp.
const int RGB_Palette_11_Size = 64
Definition at line 557 of file palettes.hpp.
double RGB_Palette_12[RGB_Palette_12_Size][3]
Initial value:
{
   { 1.0, 1.0, 1.0 },
   { 1.0, 1.0, 1.0 }
}
Definition at line 627 of file palettes.hpp.
const int RGB_Palette_12_Size = 2
Definition at line 626 of file palettes.hpp.
double RGB_Palette_13[RGB_Palette_13_Size][3]
Definition at line 681 of file palettes.hpp.
Referenced by Init_Palettes().
const int RGB_Palette_13_Size = (4*16+1)
Definition at line 680 of file palettes.hpp.
Referenced by Init_Palettes().
double RGB_Palette_14[RGB_Palette_14_Size][3]
Definition at line 684 of file palettes.hpp.
const int RGB_Palette_14_Size = 256
Definition at line 683 of file palettes.hpp.
double RGB_Palette_15[RGB_Palette_15_Size][3]
Definition at line 945 of file palettes.hpp.
const int RGB_Palette_15_Size = 256
Definition at line 944 of file palettes.hpp.
double RGB_Palette_16[RGB_Palette_16_Size][3]
Definition at line 1205 of file palettes.hpp.
const int RGB_Palette_16_Size = 256
Definition at line 1204 of file palettes.hpp.
double RGB_Palette_17[RGB_Palette_17_Size][3]
Definition at line 1466 of file palettes.hpp.
const int RGB_Palette_17_Size = 255
Definition at line 1465 of file palettes.hpp.
double RGB_Palette_18[RGB_Palette_18_Size][3]
Definition at line 1726 of file palettes.hpp.
const int RGB_Palette_18_Size = 256
Definition at line 1725 of file palettes.hpp.
double RGB_Palette_19[RGB_Palette_19_Size][3]
Definition at line 1987 of file palettes.hpp.
const int RGB_Palette_19_Size = 256
Definition at line 1986 of file palettes.hpp.
const int RGB_Palette_1_Size = 5
Definition at line 21 of file palettes.hpp.
double RGB_Palette_2[RGB_Palette_2_Size][3]
Initial value:
{
   { 1.0, 0.0, 0.0 },
   { 1.0, 0.0, 0.0 }
}
Definition at line 32 of file palettes.hpp.
double RGB_Palette_20[RGB_Palette_20_Size][3]
Definition at line 2248 of file palettes.hpp.
const int RGB_Palette_20_Size = 256
Definition at line 2247 of file palettes.hpp.
double RGB_Palette_21[RGB_Palette_21_Size][3]
Definition at line 2509 of file palettes.hpp.
const int RGB_Palette_21_Size = 256
Definition at line 2508 of file palettes.hpp.
double RGB_Palette_22[RGB_Palette_22_Size][3]
Definition at line 2770 of file palettes.hpp.
const int RGB_Palette_22_Size = 151
Definition at line 2769 of file palettes.hpp.
double RGB_Palette_23[RGB_Palette_23_Size][3]
Definition at line 2926 of file palettes.hpp.
Referenced by Init_Palettes().
const int RGB_Palette_23_Size = 6*32+1
Definition at line 2925 of file palettes.hpp.
Referenced by Init_Palettes().
double RGB_Palette_24[RGB_Palette_24_Size][3]
Initial value:
{
   {0.300725, 0.680491, 0.901701}, {0.343564, 0.712004, 0.917969},
   {0.386403, 0.743518, 0.934237}, {0.441409, 0.694656, 0.899639},
   {0.496414, 0.645794, 0.86504},  {0.550366, 0.581752, 0.822636},
   {0.604318, 0.51771,  0.780231}, {0.651771, 0.474934, 0.743461},
   {0.699224, 0.432157, 0.70669},  {0.738903, 0.424989, 0.675772},
   {0.778582, 0.417821, 0.644854}, {0.810852, 0.444937, 0.617053},
   {0.843122, 0.472052, 0.589251}, {0.868355, 0.522424, 0.564101},
   {0.893588, 0.572795, 0.538951}, {0.91124,  0.630943, 0.519525},
   {0.928891, 0.68909,  0.500098}, {0.937118, 0.739358, 0.491394},
   {0.945344, 0.789625, 0.482689}, {0.940976, 0.819233, 0.488234},
   {0.936608, 0.84884,  0.493779}, {0.915305, 0.849461, 0.511525},
   {0.894001, 0.850082, 0.529271}, {0.850401, 0.817693, 0.547873},
   {0.806801, 0.785304, 0.566474}, {0.734503, 0.71805,  0.563027},
   {0.662204, 0.650797, 0.559579}, {0.553381, 0.54463,  0.499912},
   {0.444557, 0.438462, 0.440244}, {0.289045, 0.280283, 0.282844},
   {0.133532, 0.122103, 0.125444}
}
Definition at line 2929 of file palettes.hpp.
const int RGB_Palette_24_Size = 31
Definition at line 2928 of file palettes.hpp.
double RGB_Palette_25[RGB_Palette_25_Size][3]
Definition at line 2962 of file palettes.hpp.
Referenced by Init_Visit_Calewhite_Palette().
const int RGB_Palette_25_Size = (4*16+1)
Definition at line 2961 of file palettes.hpp.
Referenced by Init_Visit_Calewhite_Palette().
const int RGB_Palette_2_Size = 2
Definition at line 31 of file palettes.hpp.
double RGB_Palette_3[RGB_Palette_3_Size][3]
Definition at line 39 of file palettes.hpp.
const int RGB_Palette_3_Size = 65
Definition at line 38 of file palettes.hpp.
double RGB_Palette_4[RGB_Palette_4_Size][3]
Initial value:
{
   { 1.0, 0.8431, 0.0 },
   { 1.0, 0.8431, 0.0 }
}
Definition at line 137 of file palettes.hpp.
const int RGB_Palette_4_Size = 2
Definition at line 136 of file palettes.hpp.
double RGB_Palette_5[RGB_Palette_5_Size][3]
Definition at line 144 of file palettes.hpp.
const int RGB_Palette_5_Size = 64
Definition at line 143 of file palettes.hpp.
double RGB_Palette_6[RGB_Palette_6_Size][3]
Definition at line 213 of file palettes.hpp.
const int RGB_Palette_6_Size = 64
Definition at line 212 of file palettes.hpp.
double RGB_Palette_7[RGB_Palette_7_Size][3]
Definition at line 282 of file palettes.hpp.
const int RGB_Palette_7_Size = 64
Definition at line 281 of file palettes.hpp.
double RGB_Palette_8[RGB_Palette_8_Size][3]
Definition at line 351 of file palettes.hpp.
const int RGB_Palette_8_Size = 64
Definition at line 350 of file palettes.hpp.
double RGB_Palette_9[RGB_Palette_9_Size][3]
Definition at line 420 of file palettes.hpp.
const int RGB_Palette_9_Size = 64
Definition at line 419 of file palettes.hpp.
int RGB_Palette_Size = RGB_Palettes_Sizes[Default_RGB_Palette]
Definition at line 2999 of file palettes.hpp.
Referenced by Make_Texture_From_Palette(), Make_Texture_From_Palette_2(), MySetColor(), and Set_Palette().
double* RGB_Palettes[Num_RGB_Palettes]
Initial value:
{
   *RGB_Palette_1, *RGB_Palette_2, *RGB_Palette_3, *RGB_Palette_4,
   *RGB_Palette_5, *RGB_Palette_6, *RGB_Palette_7, *RGB_Palette_8,
   *RGB_Palette_9, *RGB_Palette_10, *RGB_Palette_11, *RGB_Palette_12,
   *RGB_Palette_13, *RGB_Palette_14, *RGB_Palette_15, *RGB_Palette_16,
   *RGB_Palette_17, *RGB_Palette_18, *RGB_Palette_19, *RGB_Palette_20,
   *RGB_Palette_21, *RGB_Palette_22, *RGB_Palette_23, *RGB_Palette_24,
   *RGB_Palette_25
}
Definition at line 2978 of file palettes.hpp.
Referenced by Set_Palette().
const char* RGB_Palettes_Names[Num_RGB_Palettes]
Initial value:
{
   "5-color   ", "red       ", "jet-like  ", "golden    ", "bone      ",
   "hot       ", "pink      ", "cool      ", "summer    ", "hsv       ",
   "copper    ", "white     ", "vivid     ", "aluminum  ", "sunrise   ",
   "horizon   ", "hilite    ", "deep sea  ", "pastel    ", "tropical  ",
   "wood      ", "mars      ", "rainbow   ", "cmyk      ", "calewhite "
}
Definition at line 2989 of file palettes.hpp.
Referenced by Select_New_RGB_Palette().
const int RGB_Palettes_Sizes[Num_RGB_Palettes]
Initial value:
{
   RGB_Palette_1_Size, RGB_Palette_2_Size, RGB_Palette_3_Size,
   RGB_Palette_4_Size, RGB_Palette_5_Size, RGB_Palette_6_Size,
   RGB_Palette_7_Size, RGB_Palette_8_Size, RGB_Palette_9_Size,
   RGB_Palette_10_Size, RGB_Palette_11_Size, RGB_Palette_12_Size,
   RGB_Palette_13_Size, RGB_Palette_14_Size, RGB_Palette_15_Size,
   RGB_Palette_16_Size, RGB_Palette_17_Size, RGB_Palette_18_Size,
   RGB_Palette_19_Size, RGB_Palette_20_Size, RGB_Palette_21_Size,
   RGB_Palette_22_Size, RGB_Palette_23_Size, RGB_Palette_24_Size,
   RGB_Palette_25_Size
}
Definition at line 2965 of file palettes.hpp.
Referenced by Set_Palette().