GLVis: vsdata.cpp File Reference
vsdata.cpp File Reference
#include <stdlib.h>
#include <math.h>
#include <X11/keysym.h>
#include <iomanip>
#include <sstream>
#include "vsdata.hpp"
#include "aux_vis.hpp"
#include "material.hpp"
#include "gl2ps.h"
Functions
void KeyCPressed ()
void KeySPressed ()
void KeyaPressed ()
void KeylPressed ()
void KeyLPressed ()
void KeyrPressed ()
void KeyRPressed ()
void Next_RGB_Palette ()
int Select_New_RGB_Palette ()
void KeyPPressed ()
void KeyF6Pressed ()
void KeyF7Pressed ()
void KeyBackslashPressed ()
void KeyTPressed ()
void KeyGPressed ()
void KeyF1Pressed ()
void KeyF2Pressed ()
void KeykPressed ()
void KeyKPressed ()
void KeyAPressed ()
void KeyCommaPressed ()
void KeyLessPressed ()
void KeyGravePressed ()
void KeyTildePressed ()
void KeyToggleTexture ()
Variables
VisualizationSceneScalarData * vsdata
VisualizationScene * locscene
int RepeatPaletteTimes
const char * strings_on_off [] = { "off", "on" }
Function Documentation
void KeyaPressed ()
Definition at line 544 of file vsdata.cpp.
References SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyAPressed ()
Definition at line 758 of file vsdata.cpp.
References Remove_AntiAliasing(), SendExposeEvent(), Set_AntiAliasing(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyBackslashPressed ()
Definition at line 687 of file vsdata.cpp.
References SendExposeEvent().
Referenced by VisualizationSceneScalarData::Init().
void KeyCommaPressed ()
Definition at line 773 of file vsdata.cpp.
References MatAlphaCenter, SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyCPressed ()
Definition at line 532 of file vsdata.cpp.
References SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyF1Pressed ()
Definition at line 727 of file vsdata.cpp.
References VisualizationSceneScalarData::PrintState(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyF2Pressed ()
Definition at line 732 of file vsdata.cpp.
References SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyF6Pressed ()
Definition at line 656 of file vsdata.cpp.
References VisualizationSceneScalarData::EventUpdateColors(), GetUseTexture(), RepeatPaletteTimes, Select_New_RGB_Palette(), SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyF7Pressed ()
Definition at line 674 of file vsdata.cpp.
References VisualizationSceneScalarData::GetMaxV(), VisualizationSceneScalarData::GetMinV(), SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyGPressed ()
Definition at line 720 of file vsdata.cpp.
References VisualizationSceneScalarData::PrepareAxes(), SendExposeEvent(), Toggle_Background(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyGravePressed ()
Definition at line 793 of file vsdata.cpp.
References SendExposeEvent(), VisualizationSceneScalarData::ToggleRuler(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeykPressed ()
Definition at line 740 of file vsdata.cpp.
References MatAlpha, SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyKPressed ()
Definition at line 749 of file vsdata.cpp.
References MatAlpha, SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyLessPressed ()
Definition at line 783 of file vsdata.cpp.
References MatAlphaCenter, SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeylPressed ()
Definition at line 550 of file vsdata.cpp.
References SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyLPressed ()
Definition at line 560 of file vsdata.cpp.
References MySetColorLogscale, SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyPPressed ()
Definition at line 629 of file vsdata.cpp.
References VisualizationSceneScalarData::EventUpdateColors(), GetUseTexture(), Next_RGB_Palette(), SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyrPressed ()
Definition at line 567 of file vsdata.cpp.
References locscene, MainLoop(), RemoveIdleFunc(), SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneVector3d::Init(), and VisualizationSceneScalarData::Init().
void KeyRPressed ()
Definition at line 581 of file vsdata.cpp.
References locscene, MainLoop(), RemoveIdleFunc(), SendExposeEvent(), Set_Light(), and vsdata.
Referenced by VisualizationSceneVector3d::Init(), and VisualizationSceneScalarData::Init().
void KeySPressed ()
Definition at line 538 of file vsdata.cpp.
References SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyTildePressed ()
Definition at line 799 of file vsdata.cpp.
References VisualizationSceneScalarData::RulerPosition(), SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyToggleTexture ()
Definition at line 805 of file vsdata.cpp.
References SendExposeEvent(), VisualizationSceneScalarData::ToggleTexture(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void KeyTPressed ()
Definition at line 710 of file vsdata.cpp.
References Next_Material_And_Light(), SendExposeEvent(), and vsdata.
Referenced by VisualizationSceneScalarData::Init().
void Next_RGB_Palette ()
Definition at line 3136 of file palettes.hpp.
References Default_RGB_Palette, Num_RGB_Palettes, and Set_Palette().
Referenced by KeyPPressed().
int Select_New_RGB_Palette ()
Definition at line 3141 of file palettes.hpp.
References Default_RGB_Palette, Num_RGB_Palettes, RGB_Palettes_Names, and Set_Palette().
Referenced by KeyF6Pressed().
Variable Documentation
VisualizationScene* locscene
Definition at line 30 of file aux_vis.cpp.
int RepeatPaletteTimes
Definition at line 1151 of file aux_vis.cpp.
Referenced by KeyF6Pressed().
const char* strings_on_off[] = { "off", "on" }
Definition at line 1261 of file vsdata.cpp.
Referenced by VisualizationSceneScalarData::PrintState().
VisualizationSceneScalarData* vsdata
Definition at line 529 of file vsdata.cpp.
Referenced by VisualizationSceneScalarData::Init(), KeyaPressed(), KeyAPressed(), KeyCommaPressed(), KeyCPressed(), KeyF1Pressed(), KeyF2Pressed(), KeyF6Pressed(), KeyF7Pressed(), KeyGPressed(), KeyGravePressed(), KeykPressed(), KeyKPressed(), KeyLessPressed(), KeylPressed(), KeyLPressed(), KeyPPressed(), KeyrPressed(), KeyRPressed(), KeySPressed(), KeyTildePressed(), KeyToggleTexture(), KeyTPressed(), and Plane::Plane().