GLVis: vssolution3d.cpp File Reference
vssolution3d.cpp File Reference
#include <stdlib.h>
#include <iostream>
#include <math.h>
#include <X11/keysym.h>
#include "mfem.hpp"
#include "visual.hpp"
Functions
void ToggleMagicKey ()
int UnitCrossProd (double v[][3], double nor[])
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], double nor[])
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], const double p4[], double nor[])
void Set_Palette (int)
int Normalize (DenseMatrix &normals)
Variables
VisualizationSceneSolution3d * vssol3d
Function Documentation
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], double nor[])
Definition at line 449 of file vssolution3d.cpp.
References UnitCrossProd().
Referenced by VisualizationSceneSolution3d::CuttingPlaneFunc(), DrawPatch(), DrawQuad(), VisualizationSceneSolution3d::DrawRefinedSurf(), DrawTriangle(), VisualizationSceneSolution3d::LiftRefinedSurf(), VisualizationSceneVector3d::Prepare(), VisualizationSceneSolution3d::Prepare(), VisualizationSceneSolution::Prepare(), VisualizationSceneSolution3d::PrepareLevelSurf(), and VisualizationSceneVector3d::PrepareLines2().
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], const double p4[], double nor[])
Definition at line 464 of file vssolution3d.cpp.
References UnitCrossProd().
int Normalize (DenseMatrix & normals)
Definition at line 827 of file vssolution3d.cpp.
References Normalize().
Referenced by Normalize(), VisualizationSceneVector3d::PrepareFlat2(), VisualizationSceneSolution3d::PrepareFlat2(), and UnitCrossProd().
void Set_Palette (int)
Definition at line 3127 of file palettes.hpp.
References Default_RGB_Palette, RGB_Palette, RGB_Palette_Size, RGB_Palettes, RGB_Palettes_Sizes, and Set_Texture_Image().
void ToggleMagicKey ()
Definition at line 287 of file vssolution3d.cpp.
Referenced by VisualizationSceneSolution3d::Init().
int UnitCrossProd (double v[][3], double nor[])
Definition at line 423 of file vssolution3d.cpp.
References CrossProd(), InnerProd(), and Normalize().
Referenced by Compute3DUnitNormal().
Variable Documentation
VisualizationSceneSolution3d* vssol3d
Definition at line 22 of file vssolution3d.cpp.