GLVis: vssolution.cpp File Reference
vssolution.cpp File Reference
#include <stdlib.h>
#include <iostream>
#include <limits>
#include <math.h>
#include <X11/keysym.h>
#include "mfem.hpp"
#include "visual.hpp"
Functions
void KeyiPressed ()
void KeyIPressed ()
void DrawTriangle (const double pts[][3], const double cv[], const double minv, const double maxv)
void DrawQuad (const double pts[][3], const double cv[], const double minv, const double maxv)
void DrawPatch (const DenseMatrix &pts, Vector &vals, DenseMatrix &normals, const int n, const Array< int > &ind, const double minv, const double maxv, const int normals_opt)
Variables
VisualizationSceneSolution * vssol
VisualizationScene * locscene
int refine_func = 0
const int split_quads = 0
Function Documentation
void DrawPatch (const DenseMatrix & pts, Vector & vals, DenseMatrix & normals, const int n, const Array< int > & ind, const double minv, const double maxv, const int normals_opt)
Definition at line 802 of file vssolution.cpp.
References Compute3DUnitNormal(), and MySetColor().
Referenced by VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareFlat2(), VisualizationSceneSolution3d::PrepareFlat2(), and VisualizationSceneSolution::PrepareFlat2().
void DrawQuad (const double pts[][3], const double cv[], const double minv, const double maxv)
Definition at line 786 of file vssolution.cpp.
References Compute3DUnitNormal(), and MySetColor().
Referenced by VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareFlat(), VisualizationSceneSolution3d::PrepareFlat(), VisualizationSceneSolution::PrepareFlat(), and VisualizationSceneSolution::PrepareFlat2().
void DrawTriangle (const double pts[][3], const double cv[], const double minv, const double maxv)
Definition at line 770 of file vssolution.cpp.
References Compute3DUnitNormal(), and MySetColor().
Referenced by VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareFlat(), VisualizationSceneSolution3d::PrepareFlat(), VisualizationSceneSolution::PrepareFlat(), and VisualizationSceneSolution::PrepareFlat2().
void KeyiPressed ()
Definition at line 179 of file vssolution.cpp.
References SendExposeEvent().
Referenced by VisualizationSceneSolution::Init().
void KeyIPressed ()
Definition at line 224 of file vssolution.cpp.
Referenced by VisualizationSceneSolution3d::Init(), and VisualizationSceneSolution::Init().
Variable Documentation
VisualizationScene* locscene
Definition at line 32 of file aux_vis.cpp.
int refine_func = 0
Definition at line 177 of file vssolution.cpp.
const int split_quads = 0
Definition at line 930 of file vssolution.cpp.
VisualizationSceneSolution* vssol
Definition at line 23 of file vssolution.cpp.