GLVis: vssolution3d.hpp File Reference
vssolution3d.hpp File Reference
Classes
class VisualizationSceneSolution3d
Functions
double InnerProd (double a[], double b[])
void CrossProd (double a[], double b[], double cp[])
int Normalize (double v[])
int Normalize (DenseMatrix &normals)
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], double nor[])
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], const double p4[], double nor[])
Function Documentation
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], double nor[])
Definition at line 449 of file vssolution3d.cpp.
References UnitCrossProd().
Referenced by VisualizationSceneSolution3d::CuttingPlaneFunc(), DrawPatch(), DrawQuad(), VisualizationSceneSolution3d::DrawRefinedSurf(), DrawTriangle(), VisualizationSceneSolution3d::LiftRefinedSurf(), VisualizationSceneVector3d::Prepare(), VisualizationSceneSolution3d::Prepare(), VisualizationSceneSolution::Prepare(), VisualizationSceneSolution3d::PrepareLevelSurf(), and VisualizationSceneVector3d::PrepareLines2().
int Compute3DUnitNormal (const double p1[], const double p2[], const double p3[], const double p4[], double nor[])
Definition at line 464 of file vssolution3d.cpp.
References UnitCrossProd().
void CrossProd (double a[], double b[], double cp[]) [inline]
Definition at line 116 of file vssolution3d.hpp.
Referenced by UnitCrossProd().
double InnerProd (double a[], double b[]) [inline]
Definition at line 111 of file vssolution3d.hpp.
Referenced by Normalize(), VisualizationSceneSolution3d::PrepareLines2(), and UnitCrossProd().
int Normalize (double v[]) [inline]
Definition at line 123 of file vssolution3d.hpp.
References InnerProd().
int Normalize (DenseMatrix & normals)
Definition at line 827 of file vssolution3d.cpp.
References Normalize().
Referenced by Normalize(), VisualizationSceneVector3d::PrepareFlat2(), VisualizationSceneSolution3d::PrepareFlat2(), and UnitCrossProd().