GLVis: vssolution.hpp File Reference
vssolution.hpp File Reference
Classes
class VisualizationSceneSolution
Functions
void DrawTriangle (const double pts[][3], const double cv[], const double minv, const double maxv)
void DrawQuad (const double pts[][3], const double cv[], const double minv, const double maxv)
void DrawPatch (const DenseMatrix &pts, Vector &vals, DenseMatrix &normals, const int n, const Array< int > &ind, const double minv, const double maxv, const int normals_opt=0)
Function Documentation
void DrawPatch (const DenseMatrix & pts, Vector & vals, DenseMatrix & normals, const int n, const Array< int > & ind, const double minv, const double maxv, const int normals_opt = 0)
Definition at line 808 of file vssolution.cpp.
References Compute3DUnitNormal(), and MySetColor().
Referenced by VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareFlat2(), VisualizationSceneSolution::PrepareFlat2(), and VisualizationSceneSolution3d::PrepareFlat2().
void DrawQuad (const double pts[][3], const double cv[], const double minv, const double maxv)
Definition at line 792 of file vssolution.cpp.
References Compute3DUnitNormal(), and MySetColor().
Referenced by VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareFlat(), VisualizationSceneSolution3d::PrepareFlat(), VisualizationSceneSolution::PrepareFlat(), and VisualizationSceneSolution::PrepareFlat2().
void DrawTriangle (const double pts[][3], const double cv[], const double minv, const double maxv)
Definition at line 776 of file vssolution.cpp.
References Compute3DUnitNormal(), and MySetColor().
Referenced by VisualizationSceneSolution3d::PrepareCuttingPlane2(), VisualizationSceneVector3d::PrepareFlat(), VisualizationSceneSolution3d::PrepareFlat(), VisualizationSceneSolution::PrepareFlat(), and VisualizationSceneSolution::PrepareFlat2().