GLVis: vsvector.cpp File Reference
vsvector.cpp File Reference
#include <stdlib.h>
#include <iostream>
#include <limits>
#include <math.h>
#include "mfem.hpp"
#include "visual.hpp"
Functions
void KeyDPressed ()
void KeyNPressed ()
void KeyBPressed ()
void KeyvPressed ()
void KeyVPressed ()
void KeyuPressed ()
void KeyUPressed ()
double VecLength (double x, double y)
double VecDirection (double x, double y)
double VecDotNx (double x, double y)
double VecDotNy (double x, double y)
double VecDivSubst (double x, double y)
double VecCurlSubst (double x, double y)
double VecAnisotrSubst (double x, double y)
Variables
VisualizationSceneVector * vsvector
VisualizationScene * locscene
VisualizationSceneSolution * vssol
int key_u_func = 0
double(* Vec2ScalarFunctions [7])(double, double)
const char * Vec2ScalarNames [7]
double new_maxlen
Function Documentation
void KeyBPressed ()
Definition at line 109 of file vsvector.cpp.
Referenced by VisualizationSceneVector3d::Init(), VisualizationSceneVector::Init(), and VisualizationSceneSolution::Init().
void KeyDPressed ()
Definition at line 97 of file vsvector.cpp.
References SendExposeEvent().
Referenced by VisualizationSceneVector3d::Init(), and VisualizationSceneVector::Init().
void KeyNPressed ()
Definition at line 103 of file vsvector.cpp.
Referenced by VisualizationSceneVector3d::Init(), and VisualizationSceneVector::Init().
void KeyUPressed ()
Definition at line 186 of file vsvector.cpp.
References key_u_func.
Referenced by VisualizationSceneVector3d::Init(), VisualizationSceneVector::Init(), and VisualizationSceneSolution3d::Init().
void KeyuPressed ()
Definition at line 145 of file vsvector.cpp.
References VisualizationSceneVector::CycleVec2Scalar(), key_u_func, VisualizationSceneVector::PrepareVectorField(), VisualizationSceneVector::RefineFactor, SendExposeEvent(), and VisualizationSceneSolution::shading.
Referenced by VisualizationSceneVector3d::Init(), VisualizationSceneVector::Init(), and VisualizationSceneSolution3d::Init().
void KeyvPressed ()
Definition at line 128 of file vsvector.cpp.
References SendExposeEvent().
Referenced by VisualizationSceneVector3d::Init(), VisualizationSceneVector::Init(), and VisualizationSceneSolution3d::Init().
void KeyVPressed ()
Definition at line 134 of file vsvector.cpp.
References SendExposeEvent().
Referenced by VisualizationSceneVector3d::Init(), VisualizationSceneVector::Init(), and VisualizationSceneSolution3d::Init().
double VecAnisotrSubst (double x, double y)
Definition at line 290 of file vsvector.cpp.
Referenced by VisualizationSceneVector::GetRefinedValues().
double VecCurlSubst (double x, double y)
Definition at line 285 of file vsvector.cpp.
Referenced by VisualizationSceneVector::GetRefinedValues().
double VecDirection (double x, double y)
Definition at line 265 of file vsvector.cpp.
double VecDivSubst (double x, double y)
Definition at line 280 of file vsvector.cpp.
Referenced by VisualizationSceneVector::GetRefinedValues().
double VecDotNx (double x, double y)
Definition at line 270 of file vsvector.cpp.
double VecDotNy (double x, double y)
Definition at line 275 of file vsvector.cpp.
double VecLength (double x, double y)
Definition at line 260 of file vsvector.cpp.
Referenced by VisualizationSceneVector::DrawVector(), VisualizationSceneVector::Init(), and VisualizationSceneVector::NewMeshAndSolution().
Variable Documentation
int key_u_func = 0
Definition at line 143 of file vsvector.cpp.
Referenced by KeyUPressed(), and KeyuPressed().
VisualizationScene* locscene
Definition at line 30 of file aux_vis.cpp.
double new_maxlen
Definition at line 749 of file vsvector.cpp.
Referenced by VisualizationSceneVector::DrawVector(), and VisualizationSceneVector::PrepareVectorField().
double(* Vec2ScalarFunctions[7])(double, double)
Initial value:
{ VecLength, VecDirection, VecDotNx, VecDotNy, VecDivSubst, VecCurlSubst,
  VecAnisotrSubst }
Definition at line 295 of file vsvector.cpp.
Referenced by VisualizationSceneVector::CycleVec2Scalar().
const char* Vec2ScalarNames[7]
Initial value:
{ "magnitude", "direction", "x-component", "y-component", "divergence",
  "curl", "anisotropy" }
Definition at line 299 of file vsvector.cpp.
Referenced by VisualizationSceneVector::CycleVec2Scalar().
VisualizationSceneSolution* vssol
Definition at line 23 of file vssolution.cpp.
VisualizationSceneVector* vsvector
Definition at line 90 of file vsvector.cpp.